var p=void 0,q=!0,s=null,t=!1;function v(){return function(){}}var w,x=jQuery,aa={mode:"horizontal",ed:"",L:q,Cc:t,speed:500,oa:s,I:0,ia:0,$c:t,kc:t,ua:t,kd:t,wa:t,mb:500,md:q,cc:50,rd:t,qd:q,X:q,Yc:"full",Xc:" / ",Sb:s,Qa:s,cb:s,controls:q,Pb:"Next",Ub:"Prev",ab:s,eb:s,ka:t,fd:"Start",hd:"Stop",pb:t,qb:s,ja:t,pause:4E3,tb:q,Oa:"next",ic:t,rb:0,s:1,r:1,R:0,Ea:0,Kd:v(),Hd:v(),bb:v(),Id:v(),Jd:v()};function __(){};x.fn.wb=function(b){if(0!=this.length){if(1<this.length)return this.each(function(){x(this).wb(b)}),this;var a={},c=this,e=function(){var b=0,c=x();if("vertical"==a.a.mode||a.a.wa)if(a.ya){var d=1==a.a.R?a.c.index:a.c.index*j(),c=a.children.eq(d);for(i=1;a.a.r-1>=i;i++)c=d+i>=a.children.length?c.add(a.children.eq(i-1)):c.add(a.children.eq(d+i))}else c=a.children.eq(a.c.index);else c=a.children;return"vertical"==a.a.mode?(c.each(function(){b+=x(this).outerHeight()}),0<a.a.I&&(b+=a.a.I*(a.a.s-1))):
b=Math.max.apply(Math,c.map(function(){return x(this).outerHeight(t)}).get()),b},d=function(){var b=a.a.Ea,c=a.viewport.width();return 0==a.a.Ea?b=c:c>a.Mb?b=(c-a.a.I*(a.a.r-1))/a.a.r:a.Nb>c&&(b=(c-a.a.I*(a.a.s-1))/a.a.s),b},f=function(){var b=1;"horizontal"==a.a.mode?a.Nb>a.viewport.width()?b=a.a.s:a.viewport.width()>a.Mb?b=a.a.r:(b=a.children.first().width(),b=Math.floor(a.viewport.width()/b)):"vertical"==a.a.mode&&(b=a.a.s);return b},g=function(){var b=0;if(0<a.a.R)if(a.a.L)b=a.children.length/
j();else for(var c=0,d=0;a.children.length>c;)++b,c=d+f(),d+=f()>=a.a.R?a.a.R:f();else b=Math.ceil(a.children.length/f());return b},j=function(){return 0<a.a.R&&f()>=a.a.R?a.a.R:f()},l=function(){if(a.c.last)if("horizontal"==a.a.mode){var b=a.children.last(),c=b.position();n(-(c.left-(a.viewport.width()-b.width())),"reset",0)}else"vertical"==a.a.mode&&(c=a.children.eq(a.children.length-a.a.s).position(),n(-c.top,"reset",0));else c=a.children.eq(a.c.index*j()).position(),a.c.index==g()-1&&(a.c.last=
q),c!=p&&("horizontal"==a.a.mode?n(-c.left,"reset",0):"vertical"==a.a.mode&&n(-c.top,"reset",0))},n=function(b,d,e,f){if(a.hb)b="vertical"==a.a.mode?"translate3d(0, "+b+"px, 0)":"translate3d("+b+"px, 0, 0)",c.css("-"+a.za+"-transition-duration",e/1E3+"s"),"slide"==d?(c.css(a.$,b),c.bind("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd",function(){c.unbind("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd");E()})):"reset"==d?c.css(a.$,b):"ticker"==d&&(c.css("-"+a.za+
"-transition-timing-function","linear"),c.css(a.$,b),c.bind("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd",function(){c.unbind("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd");n(f.Zb,"reset",0);F()}));else{var h={};h[a.$]=b;"slide"==d?c.animate(h,e,a.a.oa,function(){E()}):"reset"==d?c.css(a.$,b):"ticker"==d&&c.animate(h,speed,"linear",function(){n(f.Zb,"reset",0);F()})}},h=function(){var b="";pagerQty=g();for(var c=0;pagerQty>c;c++){var d="";a.a.Qa&&x.isFunction(a.a.Qa)?
(d=a.a.Qa(c),a.H.addClass("bx-custom-pager")):(d=c+1,a.H.addClass("bx-default-pager"));b+='<div class="bx-pager-item"><a href="" data-slide-index="'+c+'" class="bx-pager-link">'+d+"</a></div>"}a.H.html(b)},k=function(b){a.a.ja&&c.Z();c.Ba();b.preventDefault()},m=function(b){a.a.ja&&c.Z();c.Ca();b.preventDefault()},r=function(a){c.Fa();a.preventDefault()},G=function(a){c.Z();a.preventDefault()},H=function(b){a.a.ja&&c.Z();var d=x(b.currentTarget),d=parseInt(d.attr("data-slide-index"));d!=a.c.index&&
c.Va(d);b.preventDefault()},u=function(b){"short"==a.a.Yc?a.H.html(b+1+a.a.Xc+a.children.length):(a.H.find("a").removeClass("active"),a.H.find("a").eq(b).addClass("active"))},E=function(){if(a.a.L){var b="";0==a.c.index?b=a.children.eq(0).position():a.c.index==g()-1&&a.ya?b=a.children.eq((g()-1)*j()).position():a.c.index==a.children.length-1&&(b=a.children.eq(a.children.length-1).position());"horizontal"==a.a.mode?n(-b.left,"reset",0):"vertical"==a.a.mode&&n(-b.top,"reset",0)}a.Ja=t;a.a.bb(a.children.eq(a.c.index),
a.Sc,a.c.index)},B=function(b){a.a.pb?a.controls.J.html(a.controls[b]):(a.controls.J.find("a").removeClass("active"),a.controls.J.find("a:not(.bx-"+b+")").addClass("active"))},T=function(){!a.a.L&&a.a.Cc&&(0==a.c.index?(a.controls.prev.addClass("disabled"),a.controls.next.removeClass("disabled")):a.c.index==g()-1?(a.controls.next.addClass("disabled"),a.controls.prev.removeClass("disabled")):(a.controls.prev.removeClass("disabled"),a.controls.next.removeClass("disabled")))},F=function(b){speed=b?b:
a.a.speed;b={left:0,top:0};var d={left:0,top:0};"next"==a.a.Oa?b=c.find(".bx-clone").first().position():d=a.children.first().position();n("horizontal"==a.a.mode?-b.left:-b.top,"ticker",speed,{Zb:"horizontal"==a.a.mode?-d.left:-d.top})},W=function(b){a.Ja?b.preventDefault():(a.h.Da=c.position(),b=b.originalEvent,a.h.start.x=b.changedTouches[0].pageX,a.h.start.y=b.changedTouches[0].pageY,a.viewport.bind("touchmove",sa),a.viewport.bind("touchend",ta))},sa=function(b){if(b.preventDefault(),"fade"!=a.a.mode){b=
b.originalEvent;var c=0;"horizontal"==a.a.mode?(b=b.changedTouches[0].pageX-a.h.start.x,c=a.h.Da.left+b):(b=b.changedTouches[0].pageY-a.h.start.y,c=a.h.Da.top+b);n(c,"reset",0)}},ta=function(b){a.viewport.unbind("touchmove",sa);var d=b.originalEvent;b=0;(a.h.end.x=d.changedTouches[0].pageX,a.h.end.y=d.changedTouches[0].pageY,"fade"==a.a.mode)?(d=Math.abs(a.h.start.x-a.h.end.x),d>=a.a.cc&&(a.h.start.x>a.h.end.x?c.Ba():c.Ca(),c.Z())):(d=0,"horizontal"==a.a.mode?(d=a.h.end.x-a.h.start.x,b=a.h.Da.left):
(d=a.h.end.y-a.h.start.y,b=a.h.Da.top),!a.a.L&&(0==a.c.index&&0<d||a.c.last&&0>d)?n(b,"reset",200):Math.abs(d)>=a.a.cc?(0>d?c.Ba():c.Ca(),c.Z()):n(b,"reset",200));a.viewport.unbind("touchend",ta)};c.Va=function(b,d){if(!a.Ja&&a.c.index!=b)if(a.Ja=q,a.Sc=a.c.index,a.c.index=0>b?g()-1:b>=g()?0:b,a.c.last=a.c.index>=g()-1,a.a.X&&u(a.c.index),a.a.controls&&T(),"fade"==a.a.mode)a.a.wa&&a.viewport.height()!=e()&&a.viewport.animate({height:e()},a.a.mb),a.children.filter(":visible").fadeOut(a.a.speed).css({zIndex:0}),
a.children.eq(a.c.index).css("zIndex",51).fadeIn(a.a.speed,function(){x(this).css("zIndex",50);E()});else{a.a.wa&&a.viewport.height()!=e()&&a.viewport.animate({height:e()},a.a.mb);var f=0,h={left:0,top:0};if(!a.a.L&&a.ya&&a.c.last)if("horizontal"==a.a.mode)var k=a.children.eq(a.children.length-1),h=k.position(),f=a.viewport.width()-k.width();else h=a.children.eq(a.children.length-a.a.s).position();else a.ya&&a.c.last&&"prev"==d?(h=1==a.a.R?a.a.r-j():(g()-1)*j()-(a.children.length-a.a.r),k=c.children(".bx-clone").eq(h),
h=k.position()):"next"==d&&0==a.c.index?(h=c.find(".bx-clone").eq(a.a.r).position(),a.c.last=t):0<=b&&(h=b*j(),h=a.children.eq(h).position());n("horizontal"==a.a.mode?-(h.left-f):-h.top,"slide",a.a.speed)}};c.Ba=function(){(a.a.L||!a.c.last)&&c.Va(a.c.index+1,"next")};c.Ca=function(){(a.a.L||0!=a.c.index)&&c.Va(a.c.index-1,"prev")};c.Fa=function(b){a.interval||(a.interval=setInterval(function(){"next"==a.a.Oa?c.Ba():c.Ca()},a.a.pause),a.a.ka&&1!=b&&B("stop"))};c.Z=function(b){a.interval&&(clearInterval(a.interval),
a.interval=s,a.a.ka&&1!=b&&B("start"))};c.zc=function(){return a.c.index};c.Dd=function(){return a.children.length};var ua=x(window).width(),va=x(window).height();x(window).resize(function(){var b=x(window).width(),f=x(window).height();(ua!=b||va!=f)&&(ua=b,va=f,a.children.add(c.find(".bx-clone")).width(d()),a.viewport.css("height",e()),a.c.last&&(a.c.index=g()-1),a.c.index>=g()&&(a.c.last=q),a.a.X&&!a.a.cb&&(h(),u(a.c.index)),a.a.ua||l())});a.a=x.extend({},aa,b);a.children=c.children(a.a.ed);a.a.$c&&
(a.a.ia=Math.floor(Math.random()*a.children.length));a.c={index:a.a.ia};a.ya=1<a.a.s||1<a.a.r;a.Nb=a.a.s*a.a.Ea+(a.a.s-1)*a.a.I;a.Mb=a.a.r*a.a.Ea+(a.a.r-1)*a.a.I;a.Ja=t;a.controls={};a.$="vertical"==a.a.mode?"top":"left";var O;if(O=a.a.qd)if(O="fade"!=a.a.mode)a:{O=document.createElement("div");var ha=["WebkitPerspective","MozPerspective","OPerspective","msPerspective"],Y;for(Y in ha)if(O.style[ha[Y]]!==p){O=(a.za=ha[Y].replace("Perspective","").toLowerCase(),a.$="-"+a.za+"-transform",q);break a}O=
t}a.hb=O;"vertical"==a.a.mode&&(a.a.r=a.a.s);c.wrap('<div class="bx-wrapper"><div class="bx-viewport"></div></div>');a.viewport=c.parent();a.Lb=x('<div class="bx-loading" />');a.viewport.prepend(a.Lb);c.css({width:"horizontal"==a.a.mode?215*a.children.length+"%":"auto",position:"relative"});a.hb&&a.a.oa?c.css("-"+a.za+"-transition-timing-function",a.a.oa):a.a.oa||(a.a.oa="swing");a.viewport.css({width:"100%",overflow:"hidden",position:"relative"});a.children.css({"float":"horizontal"==a.a.mode?"left":
"none",listStyle:"none"});a.children.width(d());"horizontal"==a.a.mode&&0<a.a.I&&a.children.css("marginRight",a.a.I);"vertical"==a.a.mode&&0<a.a.I&&a.children.css("marginBottom",a.a.I);"fade"==a.a.mode&&(a.children.css({position:"absolute",zIndex:0,display:"none"}),a.children.eq(a.a.ia).css({zIndex:50,display:"block"}));a.controls.Aa=x('<div class="bx-controls" />');a.a.kc&&a.children.each(function(){var a=x(this).find("img:first").attr("title");a!=p&&x(this).append('<div class="bx-caption"><span>'+
a+"</span></div>")});a.a.L&&("fade"!=a.a.mode&&!a.a.ua)&&(O="vertical"==a.a.mode?a.a.s:a.a.r,Y=a.children.slice(0,O).clone().addClass("bx-clone"),O=a.children.slice(-O).clone().addClass("bx-clone"),c.append(Y).prepend(O));a.c.last=a.a.ia==g()-1;a.a.rd&&c.Bd();a.a.ua||(a.a.X&&(a.a.cb?a.H=x(a.a.cb):(a.H=x('<div class="bx-pager" />'),a.a.Sb?x(a.a.Sb).html(a.H):a.controls.Aa.addClass("bx-has-pager").append(a.H),h()),a.H.delegate("a","click",H)),a.a.controls&&(a.controls.next=x('<a class="bx-next" href="">'+
a.a.Pb+"</a>"),a.controls.prev=x('<a class="bx-prev" href="">'+a.a.Ub+"</a>"),a.controls.next.bind("click",k),a.controls.prev.bind("click",m),a.a.ab&&x(a.a.ab).append(a.controls.next),a.a.eb&&x(a.a.eb).append(a.controls.prev),a.a.ab||a.a.eb||(a.controls.yb=x('<div class="bx-controls-direction" />'),a.controls.yb.append(a.controls.prev).append(a.controls.next),a.controls.Aa.addClass("bx-has-controls-direction").append(a.controls.yb))),a.a.ja&&a.a.ka&&(a.controls.start=x('<div class="bx-controls-auto-item"><a class="bx-start" href="">'+
a.a.fd+"</a></div>"),a.controls.stop=x('<div class="bx-controls-auto-item"><a class="bx-stop" href="">'+a.a.hd+"</a></div>"),a.controls.J=x('<div class="bx-controls-auto" />'),a.controls.J.delegate(".bx-start","click",r),a.controls.J.delegate(".bx-stop","click",G),a.a.pb?a.controls.J.append(a.controls.start):a.controls.J.append(a.controls.start).append(a.controls.stop),a.a.qb?x(a.a.qb).html(a.controls.J):a.controls.Aa.addClass("bx-has-controls-auto").append(a.controls.J),B(a.a.tb?"stop":"start")),
(a.a.controls||a.a.ka||a.a.X)&&a.viewport.after(a.controls.Aa));c.children().Ec(function(){a.Lb.remove();l();"vertical"==a.a.mode&&(a.a.wa=q);a.viewport.height(e());a.a.ja&&a.a.tb&&(0<a.a.rb?setTimeout(c.Fa,a.a.rb):c.Fa(),a.a.ic&&c.hover(function(){a.interval&&(c.Z(q),a.sb=q)},function(){a.sb&&(c.Fa(q),a.sb=s)}));if(a.a.ua){var b=0;"next"==a.a.Oa?c.append(a.children.clone().addClass("bx-clone")):(c.prepend(a.children.clone().addClass("bx-clone")),b=a.children.first().position(),b="horizontal"==a.a.mode?
-b.left:-b.top);n(b,"reset",0);a.a.X=t;a.a.controls=t;a.a.ka=t;a.a.kd&&!a.hb&&a.viewport.hover(function(){c.stop()},function(){var b=0;a.children.each(function(){b+="horizontal"==a.a.mode?x(this).outerWidth(q):x(this).outerHeight(q)});var d=a.a.speed/b*(b-Math.abs(parseInt(c.css("horizontal"==a.a.mode?"left":"top"))));F(d)});F()}a.a.X&&u(a.a.ia);a.a.controls&&T();a.a.md&&!a.a.ua&&(a.h={start:{x:0,y:0},end:{x:0,y:0}},a.viewport.bind("touchstart",W))});return this}};var y=jQuery,ba="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";
y.fn.Ec=function(b){function a(){var a=y(l),c=y(n);d&&(n.length?d.reject(g,a,c):d.resolve(g));y.isFunction(b)&&b.call(e,g,a,c)}function c(b,c){b.src===ba||-1!==y.inArray(b,j)||(j.push(b),c?n.push(b):l.push(b),y.data(b,"imagesLoaded",{Ic:c,src:b.src}),f&&d.notifyWith(y(b),[c,g,y(l),y(n)]),g.length===j.length&&(setTimeout(a),g.unbind(".imagesLoaded")))}var e=this,d=y.isFunction(y.Deferred)?y.Deferred():0,f=y.isFunction(d.notify),g=e.find("img").add(e.filter("img")),j=[],l=[],n=[];y.isPlainObject(b)&&
y.each(b,function(a,c){"callback"===a?b=c:d&&d[a](c)});g.length?g.bind("load.imagesLoaded error.imagesLoaded",function(a){c(a.target,"error"===a.type)}).each(function(a,b){var d=b.src,e=y.data(b,"imagesLoaded");e&&e.src===d?c(b,e.Ic):b.complete&&b.naturalWidth!==p?c(b,0===b.naturalWidth||0===b.naturalHeight):(b.readyState||b.complete)&&(b.src=ba,b.src=d)}):a();d&&d.promise(e)};var z=jQuery;z(document).on("click","a[data-reveal-id]",function(b){b.preventDefault();b=z(this).attr("data-reveal-id");z("#"+b).$b(z(this).data())});
z.fn.$b=function(b){b=z.extend({},{aa:"fadeAndPop",p:300,mc:q,zb:"close-reveal-modal"},b);this.each(function(){function a(){f=t}var c=z(this),e=parseInt(c.css("top")),d=c.height()+e,f=t,g=z(".reveal-modal-bg");0==g.length&&(g=z('<div class="reveal-modal-bg" />').insertAfter(c));c.bind("reveal:open",function(){g.unbind("click.modalEvent");z("."+b.zb).unbind("click.modalEvent");f||(f=q,"fadeAndPop"==b.aa&&(c.css({top:z(document).scrollTop()-d,opacity:0,visibility:"visible"}),g.fadeIn(b.p/2),c.delay(b.p/
2).animate({top:z(document).scrollTop()+e+"px",opacity:1},b.p,a())),"fade"==b.aa&&(c.css({opacity:0,visibility:"visible",top:z(document).scrollTop()+e}),g.fadeIn(b.p/2),c.delay(b.p/2).animate({opacity:1},b.p,a())),"none"==b.aa&&(c.css({visibility:"visible",top:z(document).scrollTop()+e}),g.css({display:"block"}),f=t));c.unbind("reveal:open")});c.bind("reveal:close",function(){f||(f=q,"fadeAndPop"==b.aa&&(g.delay(b.p).fadeOut(b.p),c.animate({top:z(document).scrollTop()-d+"px",opacity:0},b.p/2,function(){c.css({top:e,
opacity:1,visibility:"hidden"});f=t})),"fade"==b.aa&&(g.delay(b.p).fadeOut(b.p),c.animate({opacity:0},b.p,function(){c.css({opacity:1,visibility:"hidden",top:e});f=t})),"none"==b.aa&&(c.css({visibility:"hidden",top:e}),g.css({display:"none"})));c.unbind("reveal:close")});c.trigger("reveal:open");z("."+b.zb).bind("click.modalEvent",function(){c.trigger("reveal:close")});b.mc&&(g.css({cursor:"pointer"}),g.bind("click.modalEvent",v()));z("body").keyup(function(a){27===a.which&&c.trigger("reveal:close")})})};var ca=["Germiz by Ezelia"],da=["build v29012013.0124589.0005"];window.ad=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(b){window.setTimeout(b,1E3/60)};window.requestAnimFrame=window.ad;function A(b,a){return Math.floor(Math.random()*(a-b+1)+b)}
function ea(){for(var b="",a=0;5>a;a++)b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789*-+=^@&#?!:;$%[](){}<>".charAt(Math.floor(84*Math.random()));return b}function fa(b){for(var a=Array(Math.ceil(b.length/4)),c=0;c<a.length;c++)a[c]=b.charCodeAt(4*c)+(b.charCodeAt(4*c+1)<<8)+(b.charCodeAt(4*c+2)<<16)+(b.charCodeAt(4*c+3)<<24);return a}
function ga(b){for(var a=Array(b.length),c=0;c<b.length;c++)a[c]=String.fromCharCode(b[c]&255,b[c]>>>8&255,b[c]>>>16&255,b[c]>>>24&255);return a.join("")}function ia(b){b=b.replace(/[\u0080-\u07ff]/g,function(a){a=a.charCodeAt(0);return String.fromCharCode(192|a>>6,128|a&63)});return b=b.replace(/[\u0800-\uffff]/g,function(a){a=a.charCodeAt(0);return String.fromCharCode(224|a>>12,128|a>>6&63,128|a&63)})}
function ja(b){b=b.replace(/[\u00e0-\u00ef][\u0080-\u00bf][\u0080-\u00bf]/g,function(a){return String.fromCharCode((a.charCodeAt(0)&15)<<12|(a.charCodeAt(1)&63)<<6|a.charCodeAt(2)&63)});return b=b.replace(/[\u00c0-\u00df][\u0080-\u00bf]/g,function(a){return String.fromCharCode((a.charCodeAt(0)&31)<<6|a.charCodeAt(1)&63)})};window.__production__=q;function ka(b,a,c){var e=Math.tan(60*(2*Math.PI/360)),d=b,f=a,g=c,j,l,n;j=d/4;l=2*(d/4);n=e*j;this.Cd=function(){return d};this.Od=function(a){d=a};this.Db=function(){return j};this.Ld=function(a){j=a};this.Eb=function(){return l};this.Md=function(a){l=a};this.ha=function(){return n};this.Nd=function(a){n=a};this.pa=function(){return f};this.Pd=function(a){f=a};this.qa=function(){return g};this.Qd=function(a){g=a};this.Ta=function(a,b){var c=a.fillStyle;a.fillStyle=b||"transparent";a.beginPath();
a.moveTo(f,g);a.lineTo(f+j,g-n);a.lineTo(f+j+l,g-n);a.lineTo(f+j+j+l,g);a.lineTo(f+j+l,g+n);a.lineTo(f+j,g+n);a.lineTo(f,g);a.fill();a.stroke();a.closePath();a.fillStyle=c};this.rc=function(a,b,c){var e=a.globalAlpha,j=a.strokeStyle,l=a.lineWidth,n=a.fillStyle,E=d;0==b&&400<(new Date).getTime()%800&&(a.globalAlpha=0.5,a.fillStyle="#ff0000",a.strokeStyle="transparent",a.globalAlpha=e);b!=p&&(a.lineWidth=1,a.strokeStyle="#000000",a.font="700 "+Math.round(d/3.5)+"px Wendy One",a.fillStyle=c||"#FFFFFF",
a.fillText(b+"",f+E/2.8,g-E/4.5),a.strokeText(b+"",f+E/2.8,g-E/4.5));a.globalAlpha=e;a.strokeStyle=j;a.lineWidth=l;a.fillStyle=n};this.pc=function(a,b,c,e){var j=a.globalAlpha,l=a.strokeStyle,n=a.lineWidth,E=a.fillStyle,B=d;0==b&&400<(new Date).getTime()%800&&(a.globalAlpha=0.5,a.fillStyle="#ff0000",a.strokeStyle="transparent",a.globalAlpha=j);if(b!=p){a.lineWidth=1;a.strokeStyle="#000000";var T=Math.round(d/4.8);a.font="500 "+T+"px Wendy One";a.fillStyle="#FFFF00";a.fillText(c+"",f+B/1.5,g+B/30);
a.strokeText(c+"",f+B/1.5,g+B/30);a.font="700 "+1.4*T+"px Wendy One";a.fillStyle=e||"#FFFFFF";a.fillText(b+"",f+B/2.7,g-B/4);a.strokeText(b+"",f+B/2.7,g-B/4)}a.globalAlpha=j;a.strokeStyle=l;a.lineWidth=n;a.fillStyle=E};this.D=function(a,b){if(b&&b.e){var c=a.globalAlpha,e=a.strokeStyle,j=a.lineWidth,l=a.fillStyle,u=d||b.e.width;a.drawImage(b.e.W,b.x,b.y,b.e.width,b.e.height,f,g-n-5,u,Math.round(u*b.e.height/b.e.width));a.globalAlpha=c;a.strokeStyle=e;a.lineWidth=j;a.fillStyle=l}};this.hc=function(a,
b){if(b){var c=a.globalAlpha,e=a.strokeStyle,j=a.lineWidth,l=a.fillStyle,u=d||b.width;a.drawImage(b,0,0,b.width,b.height,f,g-n-5,u,Math.round(u*b.height/b.width));a.globalAlpha=c;a.strokeStyle=e;a.lineWidth=j;a.fillStyle=l}};this.contains=function(a,b){var c=t,d=a>=f+j&&a<=f+j+l&&b>=g-n&&b<=g+n,G=a>=f+j+l&&a<=f+j+l+j&&b>=g-(f+j+l+j-a)*e&&b<=g+(f+j+l+j-a)*e;if(a>=f&&a<=f+j&&b>=g-(a-f)*e&&b<=g+(a-f)*e||d||G)c=q;return c}};function la(b,a,c,e,d){var f=[],g=new ka(b,0,0),j=2*g.Eb()+2*g.Db(),l=g.ha(),g=g.Eb()+g.Db();this.f=b;var n=new Image;n.src="img/cell-bg.png";this.bd=function(a,b){if(a){var c=new Image;c.onload=function(){n=c;"function"==typeof b&&b()};c.src=a}};for(var h=0;h<c;h++){f[h]=[];for(var k=0;k<a;k++)f[h][k]=0==h%2?new ka(b,k*j+g+e,(h+1)*l+d):new ka(b,k*j+e,(h+1)*l+d),f[h][k].Gb=k,f[h][k].Hb=h}this.Ta=function(b){for(var d=0;d<c;d++)for(var e=0;e<a;e++)f[d][e].hc(b,n)};this.zd=function(b){for(var d=0;d<
c;d++)for(var e=0;e<a;e++)f[d][e].Ta(b)};this.vc=function(b,d){for(var e=s,g=0;g<c;g++)for(var h=0;h<a;h++)f[g][h].contains(b,d)&&(e=f[g][h],e.Gb=h,e.Hb=g);return e};this.j=function(a,b){return f[b]?f[b][a]:s}};var C=[[[0,-2],[1,-1],[1,1],[0,2],[0,1],[0,-1]],[[0,-2],[0,-1],[0,1],[0,2],[-1,1],[-1,-1]]],ma=[[[0,-4],[1,-3],[1,-2],[1,0],[1,2],[1,3],[0,4],[0,3],[-1,2],[-1,0],[-1,-2],[0,-3]],[[0,-4],[-1,-3],[1,-2],[1,0],[1,2],[-1,3],[0,4],[0,3],[-1,2],[-1,0],[-1,-2],[0,-3]]];function na(){}w=na.prototype;w.bind=function(b,a){this.i=this.i||{};this.i[b]=this.i[b]||[];this.i[b].push(a)};w.unbind=function(b,a){this.i=this.i||{};b in this.i!==t&&this.i[b].splice(this.i[b].indexOf(a),1)};w.od=function(b){this.i=this.i||{};this.i[b]=[]};w.trigger=function(b){for(var a=0;a<arguments.length-1;a++);this.i=this.i||{};if(b in this.i!==t)for(a=0;a<this.i[b].length;a++)this.i[b][a].apply(this,Array.prototype.slice.call(arguments,1))};
w.Y=function(b){this[b]=function(a,c){"function"==typeof a&&(c&&this.od(b),this.bind(b,a));return this}};var D={};D.Kb=new buzz.sound("audio/intro",{formats:["mp3","ogg"],channels:1});D.Lc=new buzz.sound("audio/lvl1",{formats:["mp3","ogg"],channels:1});D.vb=new buzz.sound("audio/bossw1",{formats:["mp3","ogg"],channels:1});D.Zc=new buzz.sound("audio/blip",{formats:["mp3","ogg"],channels:4});D.tc=new buzz.sound("audio/blip",{formats:["mp3","ogg"],channels:4});D.Ed=new buzz.sound("audio/popping",{formats:["mp3","ogg"],channels:4});D.Ob=new buzz.sound("audio/mutation1",{formats:["mp3","ogg"],channels:2});
D.ec=new buzz.sound("audio/win",{formats:["mp3","ogg"],channels:1});D.fail=new buzz.sound("audio/fail",{formats:["mp3","ogg"],channels:1});D.uc=new buzz.sound("audio/crash1",{formats:["mp3","ogg"],channels:3});for(var I=[],i=0;30>=i;i++)I[i]=D.Lc;I[15]=D.vb;I[30]=D.vb;var oa=t;window.muteAll=function(){for(var b in D)D[b].mute()};window.unmuteAll=function(){for(var b in D)D[b].unmute()};function J(b,a,c,e){this.src=b;this.width=a;this.height=c;this.a=e;var d=this;this.src=b;this.ready=t;this.W=new Image;this.W.onload=function(){d.ready=q;d.Ib=d.W.width;d.Dc=d.W.height;d.width=a||d.Ib;d.height=c||d.Dc};this.W.src=b;this.state=e||{};this.state.g=this.state.g||{};this.state.g["default"]=this.state.g["default"]||[0];this.state.frame={};for(var f in this.state.g)this.state.frame[f]=0}
J.prototype.Fb=function(b){if(this.ready){var a=this.Ib/this.width;return{x:b%a*this.width,y:Math.floor(b/a)*this.height,e:this}}};J.prototype.C=function(b){if(this.ready){var a=this.state.g[b];a||(a=this.state.g["default"]);var c=this.state.frame[b]||0;c==a.length&&(c=0);a=this.Fb(a[c]);this.state.frame[b]=c;a.e=this;return a}};J.prototype.gd=function(b){b=this.state.g[b];return!b?-1:b.length};
J.prototype.step=function(b){if(this.ready){var a=this.state.g[b.g];a||(a=this.state.g["default"]);var c=b.frame,e=(new Date).getTime();66<=e-b.Ya&&(b.Ya=e,c++,c>=a.length&&(c=0),b.frame=c);b=this.Fb(a[c]);b.e=this;return b}};
function pa(b,a,c,e,d,f,g,j,l){this.e=b;this.N=a;this.O=c;this.ma=e;this.na=d;this.interval=f;this.x=g;this.y=j;this.ac=l;this.e=b;this.x=g;this.y=j;this.N=a;this.O=c;this.ma=e;this.na=d;this.interval=f;this.ready=q;this.v=t;this.ac=l;this.scale=100;this.Ia=0.13;this.Pa=t;this.Yb()}pa.prototype.Yb=function(){var b=this;this.frame=0;this.g="default";this.Ya=(new Date).getTime();this.Pa&&clearTimeout(this.Pa);this.Pa=setTimeout(function(){b.g="idle"},5E3+A(500,1500))};
pa.prototype.update=function(){if(this.ac[this.Vb][this.Wb].ready)if(this.v=t,10>Math.abs(this.N-this.ma)&&10>Math.abs(this.O-this.na))this.ready=q,this.origin=p,this.scale=100,this.Yb();else{var b=this.N+(this.ma-this.N)*this.Ia,a=this.O+(this.na-this.O)*this.Ia;this.scale=Math.round(this.scale+0.05*(100-this.scale));this.N=b;this.O=a}};var qa=new J("img/dna.png"),ra=new J("img/hcell0.png"),wa=new J("img/hcell1.png"),xa=new J("img/hcell2.png");new J("img/virus-mut.png");new J("img/virus-jump.png");
new J("img/fx/quake_0.png",256,128,{g:{"default":[0],die:[12,13,14,15,16,17]}});function ya(b){this.ud=b;this.canvas=document.getElementById(b);this.ba=document.getElementById("bg"+b);this.Ra=this.canvas.getContext("2d");this.ub=this.ba.getContext("2d");this.xa=q;this.A={};this.T={};this.S=t;this.Fd=0}w=ya.prototype;
w.start=function(b){var a=this;this.A={};b.sc(function(b){b.e&&(a.A[b.id]=b.e);b.G&&(a.A[b.G]=b.Nc)});this.b=b;this.M=[];for(var c=0;c<b.config.grid_width;c++){this.M[c]=[];for(var e=0;e<b.config.grid_height;e++)this.M[c][e]=new pa(p,-1,-1,-1,-1,0,c,e,this.M)}this.m=[];for(c=0;c<b.config.grid_width;c++){this.m[c]=[];for(e=0;e<b.config.grid_height;e++)this.m[c][e]=this.b.grid[c][e]==p?p:JSON.parse(JSON.stringify(this.b.grid[c][e]))}this.text=[];this.U=[];this.S||(this.S=q,requestAnimFrame(function(){a.S&&
a.Ab()}))};w.ready=function(){for(var b=this.b,a=0;a<b.config.grid_width;a++)for(var c=0;c<b.config.grid_height;c++)if(this.m[a][c]&&(this.m[a][c].z||this.m[a][c].oc))return t;for(b=0;b<this.U.length;b++)if(this.U[b])return t;return q};w.stop=function(){this.S=t};w.Na=function(b){return"#"==b.charAt(0)?b.substring(1,7):b};w.bc=function(b,a){return"rgba("+parseInt(this.Na(b).substring(0,2),16)+","+parseInt(this.Na(b).substring(2,4),16)+","+parseInt(this.Na(b).substring(4,6),16)+","+a+")"};
w.clone=v();w.V=function(b,a,c){var e={v:a,text:b,alpha:1,Ha:p,x:c.left,y:c.top,color:c.color,font:c.font,border:c.border};e.Ha&&clearInterval(e.Ha);e.Ha=setInterval(function(){0>=e.v?e.alpha-=0.02:e.v-=100;e.y-=2;if(0>e.alpha||""==e.text)clearInterval(e.Ha),e.text=""},33);this.text&&this.text.push(e)};
w.Oc=function(b,a,c,e,d,f){var g=this.b.Q,j=g.j(c,e);if(j){var l=Math.round(j.pa()),n=Math.round(j.qa()-j.ha());if(j=g.j(d,f)){var g=Math.round(j.pa()),j=Math.round(j.qa()-j.ha()),h=this.M[d][f],k=this.m[d][f]&&this.m[d][f].player!=b?this.A[this.m[d][f].player]:p;h.e=qa;h.Ia=0.08;h.N=l;h.O=n;h.ma=g;h.na=j;h.Vb=c;h.Wb=e;h.x=d;h.y=f;h.scale=50;h.ready=t;h.v=!this.M[c][e].ready;h.player=b;h.origin={x:d,y:f,e:k||a}}}};
w.Pc=function(b,a,c,e,d,f){var g=this.b.Q,j=g.j(c,e);if(j&&!(c==d&&e==f)){var l=Math.round(j.pa()),n=Math.round(j.qa()-j.ha());if(j=g.j(d,f)){var g=Math.round(j.pa()),j=Math.round(j.qa()-j.ha()),h=this.M[d][f];h.frame=0;var k=this.m[d][f]&&this.m[d][f].player!=b?this.A[this.m[d][f].player]:p;h.e=a;h.Ia=0.15;h.N=l;h.O=n;h.ma=g;h.na=j;h.Vb=c;h.Wb=e;h.x=d;h.y=f;h.scale=20;h.ready=t;h.v=!this.M[c][e].ready;h.player=b;h.origin=k!=p?{x:d,y:f,e:k}:p}}};
w.Tb=function(b,a,c,e){if(b=this.b.Q.j(b,a)){a=Math.round(this.b.config.f*c.width/100);var d=Math.round(this.b.config.xb*c.height/100);this.U.push({e:c,g:"die",frame:0,x:Math.round(b.pa())-Math.round((a-this.b.config.f)/2),y:Math.round(b.qa()-b.ha())-Math.round((d-this.b.config.xb)/2),width:a,height:d,ca:e,loop:1,Ya:(new Date).getTime()})}else"function"==typeof e&&e()};
w.qc=function(b,a){var c=this.m,e=this.M[b][a],e=c[e.x][e.y],d=this.Ra,f=this.b.Q;if(c[b][a]&&c[b][a].player){var g=this.A[c[b][a].player];c[b][a].dna.jump&&f.j(b,a).D(d,g.C("jumper"));c[b][a].dna.kamikaze&&f.j(b,a).D(d,g.C("kamikaze"));c[b][a].muted&&f.j(b,a).D(d,g.C("mutation"));if(e!=p&&0<e.life&&900>e.life){var j="";1==e.life&&400<(new Date).getTime()%800&&(j="#ee0000");f.j(b,a).pc(d,e.life-1,e.dna.life-1,j)}e!=p&&(e.dna!=p&&e.dna.resistance)&&(j="#33b",1==e.dna.resistance&&400<(new Date).getTime()%
800&&(j="#ee0000"),f.j(b,a).rc(d,e.dna.resistance,j));42==c[b][a].type&&f.j(b,a).D(d,g.C(c[b][a].bonus))}};
w.Ac=function(b,a){var c=this,e=this.b.grid,d=this.m,f=JSON.parse(JSON.stringify(e[b][a])),g=0;if(e[b][a].fa&&!e[b][a].z){g=f.life;f.life=e[b][a].Tc;e[b][a].z=f.z=q;d[b][a]=f;d[b][a].oc=q;var j=g,l="decInterval_"+b+"_"+a;c.T[l]||(c.T[l]=setInterval(function(){d[b][a].life=d[b][a].fa?d[b][a].life-1:d[b][a].life;d[b][a].fa&&d[b][a].life<=j&&(clearInterval(c.T[l]),c.T[l]=t,d[b][a].z=t,e[b][a]&&(e[b][a].fa=t),d[b][a].fa=t)},100))}if(e[b][a].ga&&!e[b][a].z){g=f.dna.resistance;f.dna.resistance=d[b][a].dna.resistance;
e[b][a].z=f.z=q;d[b][a]=f;var n=g,h="decInterval_"+b+"_"+a;c.T[h]||(c.T[h]=setInterval(function(){d[b][a].dna.resistance=d[b][a].ga?d[b][a].dna.resistance-1:d[b][a].dna.resistance;d[b][a].ga&&d[b][a].dna.resistance<=n&&(clearInterval(c.T[h]),c.T[h]=t,e[b][a].z=d[b][a].z=t,e[b][a]&&(e[b][a].ga=t),d[b][a].ga=t)},100))}};
w.Ab=function(){var b=this,a=this.Ra,c=this.b.grid,e=this.m,d=this.b.config,f=this.b,g=this.b.Q,j=a.strokeStyle,l=a.lineWidth,n=a.fillStyle;a.lineWidth=0;this.xa&&(this.ub.clearRect(0,0,b.ba.width,b.ba.height),g.Ta(this.ub),this.xa=t);this.Ra.clearRect(0,0,b.canvas.width,b.canvas.height);for(var h=0;h<d.grid_width;h++)for(var k=0;k<d.grid_height;k++)if(c[h][k]&&(this.Ac(h,k),!c[h][k].fa&&!c[h][k].ga&&(e[h][k]=JSON.parse(JSON.stringify(c[h][k])),e[h][k].z=t)),e[h][k]){if(e[h][k].ib)g.j(h,k).D(a,this.A[e[h][k].player].C("default"));
else{var m=this.M[h][k],r=e[m.x][m.y];r!=p&&((m.player!=r.player||m.ready)&&!r.Sa)&&g.j(h,k).D(a,this.A[r.player].step(m));m.origin!=p&&g.j(m.origin.x,m.origin.y).D(a,m.origin.e.C("default"));if(m.ready)this.qc(h,k);else{var r=m.scale?m.scale/100:1,G=g.f||m.e.width,H=G*m.e.height/m.e.width,u=Math.round(G*(1-r)/2),E=Math.round(H*(1-r)/2),B=m.e.C("default");m.v||a.drawImage(m.e.W,B.x,B.y,m.e.width,m.e.height,m.N+u,m.O+E,G*r,H*r);m.update()}}!c[h][k]&&(e[h][k]&&!e[h][k].Sa&&!e[h][k].z)&&(e[h][k].Sa=
q,function(a,c){b.Tb(a,c,b.A[e[h][k].player],function(){e[a][c].Sa=t;e[a][c]=p})}(h,k))}for(m=0;m<this.U.length;m++)if(r=this.U[m])if(0>=r.e.gd(r.g))this.U[m]=p,"function"==typeof r.ca&&r.ca(r);else if(d=r.e.step(r))a.drawImage(d.e.W,d.x,d.y,r.e.width,r.e.height,r.x,r.y,r.width,r.height),0==r.frame&&r.frame!=r.Jc&&(0>=r.loop||!r.loop?(this.U[m]=p,"function"==typeof r.ca&&r.ca(r)):r.loop--),r.Jc=r.frame;a.lineWidth=5;a.strokeStyle="#aa0000";m=f.o?f.o.x:-1;r=f.o?f.o.y:-1;if((d=g.j(m,r))&&c[m][r]!=p&&
c[m][r].player==f.n.id){d.D(a,ra.C("default"));if(f.o.dna.jump){f=ma[r%2];for(G=0;G<f.length;G++)d=f[G],H=m+d[0],u=r+d[1],a.lineWidth=2,a.strokeStyle="#aaaa00",(d=g.j(H,u))&&c[H][u]==p&&d.D(a,xa.C("default"))}f=C[r%2];for(G=0;G<f.length;G++)d=f[G],H=m+d[0],u=r+d[1],a.lineWidth=3,a.strokeStyle="#aa0000",(d=g.j(H,u))&&c[H][u]==p&&d.D(a,wa.C("default"))}for(h=0;h<this.text.length;h++)c=this.text[h],c.text&&""!=c.text&&(g=c.x,f=c.y,a.textBaseline="middle",a.strokeStyle="rgba(0, 0, 0, "+c.alpha+")",a.lineWidth=
c.border+1,a.fillStyle=this.bc(c.color,c.alpha),a.font=c.font,a.fillText(c.text,g,f),a.strokeText(c.text,g,f),a.strokeStyle="rgba(255, 255, 255, "+c.alpha+")",a.lineWidth=c.border,a.fillStyle=this.bc(c.color,c.alpha),a.font=c.font,a.fillText(c.text,g,f),a.strokeText(c.text,g,f));a.strokeStyle=j;a.lineWidth=l;a.fillStyle=n;requestAnimFrame(function(){b.Ab()})};var K=this.sd||function(b,a){function c(){this.constructor=b}c.prototype=a.prototype;b.prototype=new c},Game;
function za(b,a){this.config=b;this.Q=this.Q=a;this.config=b;this.va=-1;this.Y("onstart");this.Y("onnextplayer");this.Y("onactionerror");this.Y("onInfect");this.Y("onMutate");this.Y("onCellDie");this.Y("onPlayerMove");this.td=v();this.jb=v();this.La=v();this.Ka=v();this.Ma=v();this.sa=t;this.i=[];this.B=[];this.entities=[];this.grid=[];for(var c=0;c<b.grid_width;c++)this.grid[c]=[];this.v=this.S=t}K(za,na);w=za.prototype;w.onGameOver=function(b){"function"==typeof b&&(this.jb=b)};
w.Wc=function(b){"function"==typeof b&&(this.La=b)};w.Vc=function(b){"function"==typeof b&&(this.Ka=b)};w.onPlayerSelect=function(b){"function"==typeof b&&(this.Ma=b)};w.nb=function(b,a,c){"function"==typeof a&&this.B.push({id:b,vd:1,ca:a,q:c})};w.yc=function(b){for(var a=0;a<this.B.length;a++)if(this.B[a].id==b)return this.B[a]};w.pd=function(b,a,c,e){for(var d=0;d<this.B.length;d++)if(this.B[d].id==b){var f=this.B[d].ca;f(this,a,c,e)}};
w.start=function(b){if(!this.S){this.S=q;this.config.players_list=[];for(var a=0;a<this.entities.length;a++)this.entities[a].Za=0,this.entities[a]instanceof L&&this.entities[a].Hc(),this.entities[a]instanceof M&&this.config.players_list.push(this.entities[a].id);this.n=p;this.next();"function"==typeof b&&b();this.trigger("onstart")}};
w.reset=function(){this.S=t;this.va=-1;this.B=[];this.entities=[];this.grid=[];for(var b=0;b<this.config.grid_width;b++)this.grid[b]=[];for(b=0;b<this.entities.length;b++)this.entities[b].w!=p&&(this.entities[b].w.terminate(),delete this.entities[b].w,this.entities[b].w=p)};w.next=function(){if(!this.v&&!this.fc()){this.lb();var b=this.n;this.va++;this.va%=this.entities.length;var a=this.entities[this.va];this.n=a;this.trigger("onnextplayer",b,this.n);a.move()&&this.next()}};
w.F=function(b){for(var a=0;a<this.entities.length;a++)if(this.entities[a].id==b)return this.entities[a];return s};w.ob=function(b){this.entities.push(b)};w.sc=function(b){if("function"==typeof b)for(var a=0;a<this.entities.length;a++)b(this.entities[a])};w.ea=function(b,a,c,e,d,f){var g=d.dna,j=this.F(d.player);if(j&&(f||!this.grid[c][e]||!(this.grid[c][e].life>d.life&&this.grid[c][e].player==d.player)))f=j.l(c,e,g),f.N=b,f.O=a,this.La(b,a,c,e,d)};
w.clone=function(b,a,c,e){this.Ka(b,a,c,e);this.grid[c][e]=JSON.parse(JSON.stringify(this.grid[b][a]))};w.nd=function(b,a,c,e){var d=this.grid[c][e].dna?JSON.parse(JSON.stringify(this.grid[c][e].dna)):{life:0,jump:0};this.Ka(b,a,c,e);this.grid[c][e]=JSON.parse(JSON.stringify(this.grid[b][a]));this.grid[c][e].dna.life=Math.max(d.life,this.grid[c][e].dna.life);this.grid[c][e].dna.jump=Math.max(d.jump,this.grid[c][e].dna.jump);this.grid[c][e].dna.kamikaze=d.kamikaze||this.grid[c][e].dna.kamikaze};
w.gc=function(){for(var b=0;b<this.config.grid_height;b++){for(var a="",c=0;c<this.config.grid_width;c++)a+=c+"x"+b,a=this.grid[c][b]===p?a+"[ - ]":a+("["+this.grid[c][b].player+"-#]");__()}};w.Rb=function(b){var a=this;if(b.move){var c=b.move;setTimeout(function(){var b=setInterval(function(){a.d.ready()&&(clearInterval(b),a.kb(c.x1,c.y1,c.x2,c.y2),a.next())},100)},200)}else this.next()};
w.lb=function(){for(var b=0;b<this.config.grid_width;b++)for(var a=0;a<this.config.grid_height;a++)this.grid[b][a]!=p&&(this.n!=p&&this.grid[b][a].player==this.n.id&&-99!=this.grid[b][a].life)&&(this.grid[b][a].life=900>this.grid[b][a].life?this.grid[b][a].life-1:this.grid[b][a].life);for(b=0;b<this.config.grid_width;b++)for(a=0;a<this.config.grid_height;a++)if(this.grid[b][a]!=p&&this.n!=p&&this.grid[b][a].player==this.n.id&&-99!=this.grid[b][a].life&&0>=this.grid[b][a].life&&-99<=this.grid[b][a].life)if(this.grid[b][a].dna.spawner){for(var c=
C[a%2],e=0;e<c.length;e++){var d=c[e],f=b+d[0],d=a+d[1];this.grid[f]!=p&&this.grid[f][d]!=p&&(this.grid[f][d].ib||!this.grid[f][d].infectable)||this.ea(b,a,f,d,this.grid[b][a],q)}this.ea(b,a,b,a,this.grid[b][a])}else{if(this.grid[b][a].dna.kamikaze){c=C[a%2];for(e=0;e<c.length;e++)if(d=c[e],f=b+d[0],d=a+d[1],!(this.grid[f]==p||this.grid[f][d]==p))if(!this.grid[f][d].dna||!(this.grid[f][d].dna.kamikaze&&0==this.grid[f][d].life))if(!this.grid[f][d].dna||!(this.grid[f][d].dna.resistance&&this.grid[f][d].dna.resistance>
this.grid[b][a].life))this.grid[f][d].Ua=q,this.Xa(f,d);this.grid[b][a].Ua=q;this.grid[b][a].kamikaze=q}this.Xa(b,a)}};w.Xa=function(b,a){this.trigger("onCellDie",b,a,this.grid[b][a]);this.grid[b][a]=p};w.Wa=function(b){for(var a=0;a<this.config.grid_width;a++)for(var c=0;c<this.config.grid_height;c++)if(!(this.grid[a][c]==p||this.grid[a][c].player==p)&&this.grid[a][c].player==b)return{x:a,y:c}};
w.fc=function(){for(var b=[],a=[],c=0,e=[],d=t,f=0;f<this.config.grid_width;f++)for(var g=0;g<this.config.grid_height;g++)if(this.grid[f][g]==p)c++,e.push([f,g]);else if(!(-1==this.grid[f][g].type||42==this.grid[f][g].type||-2==this.grid[f][g].type||0==this.grid[f][g].type||this.grid[f][g].type==p))if(-1==b.indexOf(this.grid[f][g].player)&&b.push(this.grid[f][g].player),-1==a.indexOf(this.grid[f][g].player)){for(var j=f,l=g,n=C[l%2],h=0;h<n.length;h++){var k=n[h],m=j+k[0],k=l+k[1];if(0<=m&&m<this.config.grid_width&&
0<=k&&k<this.config.grid_height&&(this.grid[m][k]==p||1==this.grid[m][k].life)){-1==a.indexOf(this.grid[f][g].player)&&(a.push(this.grid[f][g].player),d=d||2==this.grid[f][g].type);break}}if(!this.grid[j][l]||!(this.grid[j][l].dna&&0>=this.grid[j][l].dna.jump)){n=ma[l%2];for(h=0;h<n.length;h++)if(k=n[h],m=j+k[0],k=l+k[1],0<=m&&m<this.config.grid_width&&0<=k&&k<this.config.grid_height&&(this.grid[m][k]==p||1==this.grid[m][k].life)){-1==a.indexOf(this.grid[f][g].player)&&(a.push(this.grid[f][g].player),
d=d||2==this.grid[f][g].type);break}}}if(1>=a.length||0==c||1>=b.length||!d){if(2<=b.length&&1==a.length&&(d=this.F(a[0])))for(f=0;f<e.length;f++)g=e[f],d.l(g[0],g[1]);this.xc(b);return q}return t};
w.kb=function(b,a,c,e){var d=this.grid[b][a];if(!d)return t;d.x=b;d.y=a;for(var f=q,g=t,j=C[d.y%2],l=0;l<j.length;l++){var n=j[l],h=d.x+n[0],n=d.y+n[1];if(h==c&&n==e){g=q;f=t;d.life=d.dna.life;break}}if(!g&&d.dna.jump){j=ma[d.y%2];for(l=0;l<j.length;l++)if(n=j[l],h=d.x+n[0],n=d.y+n[1],h==c&&n==e){f=t;this.Xa(d.x,d.y);break}}if(f)return this.trigger("onactionerror",1),t;this.ea(b,a,c,e,d);(f=this.F(d.player))&&f.Fc();this.Gc(this.grid,c,e,d);this.trigger("onPlayerMove",this.n.id,b,a,c,e);this.Ma(this.n.id,
d.x,d.y);return q};
w.Gc=function(b,a,c,e){for(var d=e.player,f=0,g=[],j=C[c%2],l=b[a][c],n=0;n<j.length;n++){var h=j[n],k=a+h[0],h=c+h[1];if(0<=k&&k<this.config.grid_width&&0<=h&&h<this.config.grid_height&&b[k][h]!=p&&b[k][h].infectable){var m=b[k][h],r=this.F(d);if(!(m.master&&r instanceof L)&&m.player!=d&&m.dna.resistance&&0<m.dna.resistance)if(m.ga=q,l.fa=q,l.Tc=l.life,m.dna.resistance<l.life)l.life-=m.dna.resistance,m.dna.resistance=0;else{m.dna.resistance-=l.life;l.life=0;return}}}for(n=0;n<j.length;n++)h=j[n],
k=a+h[0],h=c+h[1],0<=k&&(k<this.config.grid_width&&0<=h&&h<this.config.grid_height&&b[k][h]!=p&&b[k][h].infectable)&&(m=b[k][h],r=this.F(d),m.master&&r instanceof L||(m.bonus&&g.push({x:k,y:h,id:m.bonus}),m.player!=d?(f++,(!m.dna.resistance||0>=m.dna.resistance)&&this.ea(a,c,k,h,l)):(k!=e.x||h!=e.y)&&this.nd(a,c,k,h)));this.trigger("onInfect",d,f,g);this.Rc(d,g)};
w.Rc=function(b,a){for(var c=0;c<a.length;c++){var e=this.grid[a[c].x][a[c].y];e.mutable&&(this.pd(a[c].id,a[c].x,a[c].y,b),e.muted=q,this.trigger("onMutate",b,a[c]))}};
w.xc=function(b){this.lb();b={Bb:b};for(var a=0;a<this.entities.length;a++)if(this.entities[a],this.entities[a]instanceof M)b[this.entities[a].id]={ta:0,life:0};for(a=0;a<this.config.grid_width;a++)for(var c=0;c<this.config.grid_height;c++)this.grid[a][c]!=p&&b[this.grid[a][c].player]&&(b[this.grid[a][c].player].ta++,b[this.grid[a][c].player].life+=this.grid[a][c].life);for(a=0;a<this.entities.length;a++)this.entities[a].w!=p&&(this.entities[a].w.terminate(),delete this.entities[a].w,this.entities[a].w=
p);this.jb(b)};Game=za;function Aa(b,a){this.life=b;this.resistance=0;this.jump=a||0;this.master=p;this.mutable=q}Aa.prototype.wc=function(b){b&&(this.life=parseInt(b.life)||this.life,this.resistance=parseInt(b.resistance)||this.resistance,this.jump=parseInt(b.jump)||this.jump,this.master=b.master||this.master,this.kamikaze=b.kamikaze||this.kamikaze,this.spawner=b.spawner||this.spawner,this.mutable=b.mutable!=p?b.mutable:this.mutable)};
Aa.prototype.ld=function(){return{life:this.life,resistance:this.resistance,jump:this.jump,master:this.master,kamikaze:this.kamikaze,spawner:this.spawner,mutable:this.mutable}};var Entity;function Ba(b,a,c,e){this.id=b;this.K=a;this.life=c;this.b=e;this.id=b;this.life=c||900;this.type=-2;this.b=e;this.master=t;this.e=a instanceof J?a:new J(a);this.Za=0}
Ba.prototype.l=function(b,a,c){if(!this.b||!this.b.grid||!this.b.grid[b])return t;var e=new Aa(this.life,0);e.wc(c);c=e.life&&e.life>this.life?e.life:this.life;e.life=c;this.b.grid[b][a]={type:this.type,player:this.id,life:c,master:this.master,mutable:e.mutable,infectable:q,dna:e.ld()};return this.b.grid[b][a]};Ba.prototype.Fc=function(){this.Za++};Ba.prototype.move=function(){return q};Entity=Ba;var M,Ca=Entity;
function Da(b,a,c,e){Ca.call(this,b,a,c,e);this.id=b;this.K=a;this.life=c;this.type=1}K(Da,Ca);Da.prototype.move=function(){return t};var Ea=M=Da;function N(b,a,c,e){Ea.call(this,b,a,c,e);this.id=b;this.K=a;this.life=c;this.type=2}K(N,Ea);var L,Fa=M;function Ga(b,a,c,e,d){Fa.call(this,b,a,c,d);this.id=b;this.K=a;this.type=3;d&&(this.config=JSON.parse(JSON.stringify(d.config)),this.config.heuristic=e||this.config.heuristic,this.config.player=b)}K(Ga,Fa);
Ga.prototype.l=function(b,a,c){c==p&&(c={});c.mutable==p&&(c.mutable=t);return Fa.prototype.l.call(this,b,a,c)};Ga.prototype.Hc=function(){var b=this;this.w=new Worker("js/aiw.js");this.w.postMessage({action:"init",player:this.id,config:this.config});this.w.onmessage=function(a){a.data?"move"==a.data.type?b.b.Rb(a.data):__():__()};this.w.onerror=v()};
Ga.prototype.move=function(){this.b.gc();this.w.postMessage({action:"move",players_list:this.b.config.players_list,grid:this.b.grid,ptype:this.type});return t};var Ha=L=Ga;function P(b,a,c,e,d,f,g){Ha.call(this,b,c,d,f,g);this.id=b;this.G=a;this.K=c;this.Mc=e;this.G=a;this.Nc=e instanceof J?e:new J(e);this.type=6;this.master=b;this.Jb=t}K(P,Ha);
P.prototype.l=function(b,a,c){c=c||{};this.Jb?(this.type=3,b=Ha.prototype.l.call(this,b,a,c),b.master=t,this.type=6):(c.master=this.G,c.life=900,b=Ha.prototype.l.call(this,b,a,c),c.life=this.life,b.player=this.G,b.bonus=c.bonus,this.Jb=q);return b};P.prototype.move=function(){var b=this.b.Wa(this.G);if(this.b.Wa(this.id)==p&&b!=p){for(var a=0;30>a;a++){var c=A(0,this.b.config.grid_width-1),e=A(0,this.b.config.grid_height-1);if(this.b.grid[c][e]==p){this.b.ea(b.x,b.y,c,e,{player:this.id});break}}return q}return Ha.prototype.move.call(this)};
function Ia(b,a,c,e,d,f,g){P.call(this,b,a,c,e,d,f,g);this.id=b;this.G=a;this.K=c;this.Mc=e}K(Ia,P);Ia.prototype.l=function(b,a,c){if((b=P.prototype.l.call(this,b,a,c))&&c)b.Qb=c.resistance;return b};
Ia.prototype.move=function(){var b=this.b.Wa(this.G);if(b)for(var a=0;30>a;a++){var c=A(0,this.b.config.grid_width-1),e=A(0,this.b.config.grid_height-1);if(this.b.grid[c][e]==p){a=this.b.grid[b.x][b.y];if(a.Qb==a.dna.resistance)break;a.Qb=a.dna.resistance;this.b.grid[b.x][b.y]=p;this.b.grid[c][e]=a;this.b.La(b.x,b.y,c,e,a);break}}return P.prototype.move.call(this)};var Ja=M;
function Ka(b,a,c,e,d){Ja.call(this,b,a,c,d);this.id=b;this.K=a;d!=p&&(this.type=e?5:4,d.sa==t&&(a=new EURECA,d.sa=a,a.Ad.Qc=function(a,b,c,e,n){d.n.id==a&&d.Rb({move:{x1:b,y1:c,x2:e,y2:n}})},d.onPlayerMove(function(a,b,c,e,n){d.sa.Qc(a,b,c,e,n)})),e||d.sa.ready(function(){d.sa.Gd(b,"arena")}))}K(Ka,Ja);Ka.prototype.postMessage=v();var La=Entity;function Q(b,a,c){La.call(this,b,a,p,c);this.id=b;this.K=a;this.type=-1;this.ib=q}K(Q,La);
Q.prototype.l=function(b,a){if(!this.b||!this.b.grid||!this.b.grid[b])return t;this.b.grid[b][a]={player:this.id,life:-99,ib:q};return this.b.grid[b][a]};var Ma=Entity;function R(b,a,c,e,d){Ma.call(this,b,a,c,d);this.id=b;this.K=a;this.Xb=e;this.type=42;this.life=c||-99;this.Xb=e||100}K(R,Ma);
R.prototype.l=function(b,a,c){if(!this.b||!this.b.grid||!this.b.grid[b])return t;var e;c?e="string"==typeof c?c:c.bonus:(c=this.b.B[A(0,this.b.B.length)-1],A(0,100)<this.Xb&&(e=c?c.id:p));this.b.grid[b][a]={player:this.id,life:this.life,infectable:q,bonus:e,type:this.type,dna:{life:this.life}};return this.b.grid[b][a]};R.prototype.move=function(){var b=A(0,this.b.config.grid_width-1),a=A(0,this.b.config.grid_height-1);this.b.grid[b][a]==p&&this.b.ea(p,p,b,a,{player:this.id});return q};
function S(b,a,c){R.call(this,b,a,p,100,c);this.id=b;this.K=a}K(S,R);S.prototype.l=function(b,a,c){return R.prototype.l.call(this,b,a,c)};S.prototype.move=function(){return q};function A(b,a){return Math.floor(Math.random()*(a-b+1)+b)}var Na=new J("img/fx/quake_0.png",256,128,{g:{"default":[0],die:[12,13,14,15,16,17]}});
function Oa(){this.Cb=v();this.d=new ya("canvas");this.Bc();this.la={};this.la["life +2"]={q:'<div class="mutation-desc" style="background:url(img/life-muation-info.png) no-repeat" ><span class="life1">3</span><span class="lifearrow">+2</span><span class="life2">5</span></div>',fn:function(b,a,c){b.grid[a][c]&&(b.grid[a][c].dna.life+=2,b.grid[a][c].life=b.grid[a][c].dna.life)}};this.la.jumper={q:'<div class="mutation-desc" style="background:url(img/jump-muation-info.png) no-repeat" >&nbsp;</div>',
fn:function(b,a,c){b.grid[a][c]&&(b.grid[a][c].dna.jump=1)}};this.la.kamikaze={q:'<div class="mutation-desc" style="background:url(img/kamikaze-muation-info.png) no-repeat" >&nbsp;</div>',fn:function(b,a,c){b.grid[a][c]&&(b.grid[a][c].dna.kamikaze=q)}};this.$a={}}w=Oa.prototype;
w.nc=function(b){var a=b.f||100,c=b.top||0,e=b.left||0;b.config.f=a;b.config.xb=88*b.config.f/100;a=new la(a,b.config.grid_width,b.config.grid_height,e,c);a=new Game(b.config,a);a.a=b;c=1;for(e=0;e<b.players.length;e++){var d=b.players[e];d.id=c++;var f=new d.entity;if(f!=p){d.params==p&&(d.params=[]);if(d.entity==P||d.entity==Ia)d.G=c++,d.params.unshift(d.G);d.params.unshift(d.id);d.params.push(a);d.entity.apply(f,d.params);a.ob(f);if(d.pos!=p)for(var g=0;g<d.pos.length;g++){var j=d.pos[g];f.l(j[0],
j[1],d.prop)}}}if(b.bonus)for(c=0;c<b.bonus.length;c++){e=b.bonus[c];d=e.fn;if("function"!=typeof d){f=this.la[e.id];if(f==p||f.fn==p)continue;d=f.fn;e.q=f.q}a.nb(e.id,d,e.q)}this.cd(a);this.Ga="00:00:00";this.time=0;return a};
w.ra=function(b){this.Ga="00:00:00";this.time=0;clearInterval(this.dc);b.reset();for(var a=b.a,c=0;c<a.players.length;c++){var e=a.players[c],d=new e.entity;if(d!=p&&(e.entity.apply(d,e.params),b.ob(d),e.pos!=p))for(var f=0;f<e.pos.length;f++){var g=e.pos[f];d.l(g[0],g[1],e.prop)}}if(a.bonus)for(c=0;c<a.bonus.length;c++){e=a.bonus[c];d=e.fn;if("function"!=typeof d){f=this.la[e.id];if(f==p||f.fn==p)continue;d=f.fn;e.q=f.q}b.nb(e.id,d,e.q)}return b};
w.gb=function(b){var a=this;this.$a={};b.start(function(){b.d=a.d;b.a.k!=p&&b.Q.bd(b.a.k,function(){a.d.xa=q});a.d.xa=q;a.d.start(b);a.d.b.data={t:-1,u:-1};b.Wc(function(b,c,f,g,j){b!=p&&c!=p&&a.d.Pc(j.player,a.d.A[j.player],b,c,f,g)});b.Vc(function(c,d,f,g){if(c!=p&&d!=p&&b.grid[f][g]!=p&&b.grid[c][d]!=p){var j=b.grid[c][d];a.d.Oc(j.player,a.d.A[j.player],c,d,f,g)}});b.onCellDie(function(b,c,f){f.Ua&&a.d.Tb(b,c,Na)});var c=0;a.dc=setInterval(function(){c++;var b=c,d=Math.floor(c/10),b=c%10,f=Math.floor(d/
60),d=d%60,b=""+b,d=10<=d?""+d:"0"+d,f=10<=f?""+f:"0"+f;a.Ga=f+":"+d+":"+b;a.time=c;$("#timer").html(f+":"+d+":"+b)},100)})};w.jd=function(){clearInterval(this.dc)};w.Uc=function(b){"function"==typeof b&&(this.Cb=b)};
w.cd=function(b){function a(a,b,c,j,l,n){e.V(a,1E3,{left:b,top:c,color:j,font:l,border:n})}var c=this,e=c.d;b.onnextplayer(function(a,b){b instanceof N?$("#canvas").css("cursor","url('img/pointer.cur'), pointer"):$("#canvas").css("cursor","url('img/not-allowed.cur'), pointer")});b.onPlayerMove(function(a){$("#moves").html(b.F(a).Za)});b.onactionerror(function(a){switch(a){case 1:e.V("太远了",1E3,{left:100,top:170,color:"#FF0000",font:"italic 20px Chango",border:1});break;case 2:e.V("还没到你",
1E3,{left:100,top:170,color:"#FF0000",font:"italic 20px Chango",border:1});break;case 3:e.V("不是你的细胞",1E3,{left:100,top:170,color:"#FF0000",font:"italic 20px Chango",border:1})}});b.onGameOver(function(a){for(var f=0,g=0,j=0;j<a.Bb.length;j++){var l=a.Bb[j],n=b.F(l);n instanceof N||n instanceof N?f+=a[l]&&a[l].ta?a[l].ta:0:g+=a[l]&&a[l].ta?a[l].ta:0}j=t;f>g&&(j=q,e.V("好样的 :)",5E3,{left:100,top:170,color:"#00EE00",font:"italic 50px Chango",border:3}));f<g&&e.V("失败 :(",5E3,{left:100,
top:170,color:"#EE0000",font:"italic 50px Chango",border:3});f==g&&e.V("平手",5E3,{left:100,top:170,color:"#000000",font:"italic 50px Chango",border:3});c.Cb(b,a,j,f,g)});b.onInfect(function(c,e){var g=b.F(c);g&&g instanceof N&&(g="+"+e,3>e&&0<e&&a(g,100,250,"#FFE000","italic 50px Chango",5),3==e&&a(g+" 不错!",100,250,"#FFE000","italic 50px Chango",5),4==e&&a(g+" 厉害!",100,250,"#FFE000","italic 50px Chango",5),5==e&&a(g+" 太强了!",100,250,"#FFE000","italic 50px Chango",5),6==e&&a(g+" 太完美了!",
100,250,"#FFE000","italic 50px Chango",5))});b.onMutate(function(d,e){if(b.F(d)instanceof N){var g=e.id;if(!c.$a[g]){c.$a[g]=q;b.v=q;var j=b.yc(g)||{q:""};
setTimeout(function(){
	if (g == 'jumper') {
		g = '跳跃者';
	}
	else if(g == 'life +2') {
		g = '生命值+2';
	};
	alertify.alert("你获得了<b>"+g+"</b>变异 ! <br />"+j.q,function(){b.v=t;b.next()})},500)}
	if (g == 'jumper') {
		g = '跳跃者';
	}
	else if(g == 'life +2') {
		g = '生命值+2';
	};
	a("变异("+g+")",50,200,"#000055","italic 20px Chango",1)}else a("敌人变异("+e.id+")",50,200,"#550000","italic 20px Chango",1)})};
w.Bc=function(){function b(b,e){var d=e.b;if(e.ready()){if(d!=p){var f=e.canvas,g=d.Q,j=-1,l=-1,n=-1,h=-1;-1!=d.data.t&&-1!=d.data.u&&(j=d.data.t,n=d.data.u);d.data.t=-1;d.data.u=-1;b.pageX||b.pageY?(l=b.pageX,h=b.pageY):(l=b.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,h=b.clientY+document.body.scrollTop+document.documentElement.scrollTop);var k=a.d.canvas,m=0,r=0,G=q;do{var m=m+k.offsetLeft,r=r+k.offsetTop,H=getComputedStyle(k,s),u=parseInt(H.getPropertyValue("border-top-width"),
10),E=parseInt(H.getPropertyValue("border-left-width"),10),r=r+u,m=m+E;G&&(G=parseInt(H.getPropertyValue("padding-top"),10),H=parseInt(H.getPropertyValue("padding-left"),10),r+=G,m+=H);G=t}while(k=k.offsetParent);l-=f.offsetLeft+m;h-=f.offsetTop+r;f=g.vc(l,h);if(f!=s){d.data.t=f.Gb;d.data.u=f.Hb;f=d.grid[d.data.t][d.data.u];if(5==d.n.type){d.data.t=-1;d.data.u=-1;d.o=p;return}if(f){if(2!=f.type&&4!=f.type){d.trigger("onactionerror",3);d.data.t=-1;d.data.u=-1;d.o=p;return}if(f.player!=
d.n.id){d.trigger("onactionerror",2);d.data.t=-1;d.data.u=-1;d.o=p;return}d.o=f;d.o.x=d.data.t;d.o.y=d.data.u;d.Ma(d.n.id,d.o.x,d.o.y);return}}-1!=j&&-1!=n&&(l=d.data.t,h=d.data.u,d.kb(j,n,l,h)?(setTimeout(function(){var a=setInterval(function(){e.ready()&&(d.next(),clearInterval(a))},100)},500),d.data.t=-1,d.data.u=-1,d.o=p):(d.data.t=j,d.data.u=n))}}else d.trigger("onactionerror",2)}var a=this;this.d.lc=function(c){b(c,a.d)};this.d.canvas.addEventListener("click",this.d.lc,t)};function Pa(b,a,c){this.xd=b;this.width=a;this.height=c;this.canvas=$("#canvas");this.ba=$("#bgcanvas");this.yd=0;this.wd=$(b);this.fb={};var e=this;$(document).on("click",".nextLvl",function(){var a=$(this).attr("rel");e.P(a);return t})}Pa.prototype.da=function(b,a,c){a=$(a);this.fb[b]=a;this.fb[b].jc=c};
Pa.prototype.P=function(b){if(this.Kc!=b){this.Kc=b;var a=this.fb[b];a&&(b=a.jc,"canvas"!=a.attr("id")?(this.ba.fadeOut("slow"),this.canvas.fadeOut("slow",function(){$("#screen").html(a.html()).hide().fadeIn("slow")})):this.dd(),b!=p&&"function"==typeof b&&b())}};Pa.prototype.dd=function(){var b=this;$("#screen").fadeOut("slow",function(){$("#screen").html("");b.ba.fadeIn("slow");b.canvas.fadeIn("slow")})};var U=[],V=new J("img/bonus-sprite.png",100,88,{g:{"default":[0],"life +2":[1],jumper:[2],kamikaze:[3]}}),X=new J("img/germy-sprite.png",100,88,{g:{"default":[0],jumper:[3],mutation:[4],kamikaze:[5],idle:[0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1],die:[0,0]}}),Z=new J("img/glob1-sprite.png",100,88,{g:{"default":[0],jumper:[3],mutation:[4],kamikaze:[5],idle:[0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1],die:[0,0]}});
U[1]={k:"img/lvl1-cell-bg.png",f:120,top:50,left:50,d:{canvas:"canvas"},config:{depth:1,hrand:100,grid_width:3,grid_height:6,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{entity:N,params:[X,900],pos:[[0,2]]},{entity:L,params:["img/globul2.png",900,"occure"],pos:[[1,2]]}]};
U[2]={k:"img/lvl2-cell-bg.png",f:100,top:50,left:50,d:{canvas:"canvas"},config:{depth:1,hrand:90,grid_width:3,grid_height:8,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{entity:N,params:[X,900],pos:[[0,2]]},{entity:S,params:[V],pos:[[1,0],[1,2],[1,3],[1,5],[0,6]]},{entity:L,params:["img/globul2.png",900,"occure"],pos:[[2,2]]}]};
U[3]={k:"img/lvl3-cell-bg.png",f:80,top:50,left:50,d:{canvas:"canvas"},config:{depth:1,grid_width:4,grid_height:10,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{id:1,entity:N,params:[X,900],pos:[[1,3]]},{id:2,entity:L,params:["img/globul.png",900,"occure"],pos:[[0,1],[0,3],[1,0],[1,1],[1,4],[2,1],[2,3]]}]};
U[4]={k:"img/lvl4-cell-bg.png",f:100,top:20,left:20,d:{canvas:"canvas"},config:{depth:1,hrand:60,grid_width:4,grid_height:9,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{id:2,entity:L,params:["img/globul.png",900,"occure"],pos:[[2,4]]},{id:1,entity:N,params:[X,900],pos:[[0,2]]}]};
U[5]={k:"img/lvl5-cell-bg.png",f:110,top:50,left:50,d:{canvas:"canvas"},config:{depth:1,hrand:99,grid_width:4,grid_height:7,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{entity:N,params:[X,900],pos:[[0,3]]},{entity:L,params:["img/globul.png",900,"occure"],prop:{jump:0},pos:[[3,4],[3,6],[2,6],[2,0]]},{entity:Q,params:["img/wall.png"],prop:"jumper",pos:[[1,4],[1,2],[3,0]]},{entity:S,params:[V],pos:[[1,6]]}]};
U[6]={k:"img/lvl6-cell-bg.png",f:100,top:10,left:10,d:{canvas:"canvas"},config:{depth:1,hrand:30,grid_width:5,grid_height:9,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{entity:N,params:[X,900],pos:[[1,3]]},{entity:L,params:["img/globul.png",900,"occure"],prop:{jump:0},pos:[[3,4],[3,3],[3,5]]},{entity:Q,params:["img/wall.png"],prop:"jumper",pos:[[0,2],[0,7],[1,2],[1,8],[2,2],[2,4],[3,6],[4,5],[0,4],[1,1],[1,5]]}]};
U[7]={k:"img/lvl7-cell-bg.png",f:95,top:30,left:30,d:{canvas:"canvas"},config:{depth:1,grid_width:5,grid_height:8,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{entity:N,params:[X,900],pos:[[0,5]]},{entity:S,params:[V],prop:"jumper",pos:[[0,0]]},{entity:L,params:["img/globul.png",900,"occure"],prop:{jump:0},pos:[[3,0],[3,2],[3,4]]},{entity:Q,params:["img/wall.png"],prop:"jumper",pos:[[1,1],[1,3],[1,5],[1,7]]}],bonus:[{id:"jumper"}]};
U[8]={k:"img/lvl8-cell-bg.png",f:95,top:30,left:30,d:{canvas:"canvas"},config:{depth:1,grid_width:5,grid_height:8,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{entity:N,params:[X,900],pos:[[1,2]]},{entity:S,params:[V],prop:"jumper",pos:[[0,0]]},{entity:L,params:["img/globul.png",900,"occure"],prop:{jump:0},pos:[[0,7],[0,6],[1,7],[3,1],[3,3],[3,4],[4,0],[4,2],[4,4],[4,3],[4,5],[4,7]]}],bonus:[{id:"jumper"},{id:"life +2"}]};
U[9]={k:"img/lvl9-cell-bg.png",f:80,top:10,left:40,d:{canvas:"canvas"},config:{depth:1,grid_width:6,grid_height:12,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{entity:N,params:[X,900],pos:[[3,11]]},{entity:L,params:["img/globul.png",900,"occure"],prop:{jump:0},pos:[[0,0],[1,0],[2,0],[3,0],[4,0],[0,1],[1,1],[2,1],[3,1],[4,1]]},{entity:S,params:[V],prop:"jumper",pos:[[5,8]]},{entity:Q,params:["img/wall.png"],prop:"jumper",pos:[[5,6],[5,7],[4,8],[4,9],[3,8],[3,9],[2,8],[2,9],
[1,8],[1,9],[0,8],[0,5],[0,4],[1,5],[1,4],[2,5],[2,4],[3,5],[3,4],[4,5],[4,4],[5,3],[5,11]]}],bonus:[{id:"jumper"},{id:"life +2"}]};
U[10]={k:"img/lvl10-cell-bg.png",f:95,top:10,left:30,d:{canvas:"canvas"},config:{depth:1,grid_width:5,grid_height:10,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{entity:N,params:[X,5],pos:[[3,9]]},{entity:L,params:["img/globul.png",5,"occure"],prop:{jump:0},pos:[[0,2],[3,2],[1,6],[4,0],[4,1],[3,0]]},{entity:S,params:[V],prop:"jumper",pos:[[5,8]]},{entity:Q,params:["img/wall.png"],prop:"jumper",pos:[[2,5],[2,4],[3,3]]}]};
U[11]={k:"img/lvl11-cell-bg.png",f:80,top:10,left:40,d:{canvas:"canvas"},config:{depth:1,hrand:80,grid_width:6,grid_height:12,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{entity:N,params:[X,4],pos:[[0,3]]},{entity:L,params:["img/globul3.png",6,"occure"],prop:{jump:0},pos:[[5,8],[5,9],[5,10],[5,11],[4,2],[4,4],[4,6],[3,10],[3,11]]},{entity:S,params:[V],pos:[[1,9],[1,10],[2,7],[2,9],[3,1],[3,2],[3,4],[3,5],[2,2]]},{entity:S,params:[V],prop:"life +2",pos:[[1,6]]},{entity:Q,params:["img/wall.png"],
prop:"jumper",pos:[[1,1],[1,3],[1,5],[1,7],[1,11],[2,8],[2,6],[2,4],[2,0],[2,10]]}],bonus:[{id:"jumper"},{id:"life +2"}]};
U[12]={k:"img/lvl12-cell-bg.png",f:80,top:10,left:40,d:{canvas:"canvas"},config:{depth:1,hrand:90,grid_width:6,grid_height:12,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{entity:N,params:[X,3],pos:[[0,1]]},{entity:L,params:["img/globul.png",3,"occure"],prop:{jump:0},pos:[[5,8],[5,9],[5,10],[5,11],[4,2],[4,4],[4,6],[3,10],[3,11]]},{entity:S,params:[V],pos:[[0,5],[0,6],[0,7],[0,8],[0,9],[0,10],[0,11],[0,0],[1,0],[1,2],[1,4],[1,6],[1,8],[1,10],[1,11],[2,1],[2,3],[2,5],[2,7],[2,
9],[2,11]]},{entity:S,params:[V],prop:"life +2",pos:[[1,4]]},{entity:Q,params:["img/wall.png"],prop:"jumper",pos:[[1,1],[1,3],[1,5],[1,7],[1,9],[2,8],[2,6],[2,4],[2,2],[2,10]]}],bonus:[{id:"jumper"},{id:"life +2"}]};
U[13]={k:"img/lvl13-cell-bg.png",f:80,top:10,left:40,d:{canvas:"canvas"},config:{depth:1,grid_width:6,grid_height:12,hrand:90,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{entity:N,params:[X,6],pos:[[0,5]]},{entity:L,params:["img/globul2.png",5,"occure"],prop:{jump:0},pos:[[4,8],[4,10],[5,8],[5,9],[5,10],[5,11]]},{entity:L,params:["img/globul3.png",6,"occure"],prop:{jump:0},pos:[[3,3],[3,5],[3,7],[2,4],[2,6],[2,8]]},{entity:S,params:[V],prop:"jumper",pos:[[1,11]]},{entity:Q,
params:["img/wall.png"],pos:[[2,1],[2,3],[2,5],[2,7],[2,9],[2,11]]}],bonus:[{id:"jumper"}]};
U[14]={k:"img/lvl14-cell-bg.png",f:80,top:10,left:40,d:{canvas:"canvas"},config:{depth:1,grid_width:6,grid_height:12,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{entity:N,params:[X,5],pos:[[2,4]]},{entity:L,params:["img/globul3.png",6,"occure"],prop:{jump:0},pos:[[4,8],[4,10],[5,8],[5,9],[5,10],[5,11]]},{entity:L,params:["img/globul.png",5,"occure"],prop:{jump:0},pos:[[1,3],[1,5],[1,7],[0,4],[0,6],[0,8]]},{entity:S,params:[V],pos:[[1,10],[4,1]]},{entity:Q,params:["img/wall.png"],
prop:"jumper",pos:[[1,0],[1,2],[1,4],[1,6],[1,8],[4,3],[4,5],[4,7],[4,9],[4,11]]}]};
U[15]={k:"img/lvl15-cell-bg.png",f:75,d:{canvas:"canvas"},config:{depth:1,grid_width:7,hrand:30,grid_height:14,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{entity:N,params:[X,4],pos:[[0,2]]},{entity:L,params:["img/globul3.png",6,"occure"],prop:{jump:0},pos:[[5,2]]},{entity:P,params:["img/globul1.png","img/mglobul1.png",6,"occure"],prop:{bonus:"Jumper"},pos:[[6,1]]},{entity:P,params:["img/globul2.png","img/mglobul2.png",6,"occure"],prop:{bonus:"life +2"},pos:[[0,11]]},{entity:Q,
params:["img/wall.png"],prop:"jumper",pos:[[5,1],[5,3],[5,5],[5,6],[6,7],[0,7],[0,8],[0,10],[0,12],[0,13]]}],bonus:[{id:"Jumper",q:'<div class="mutation-desc" style="background:url(img/jump-muation-info.png) no-repeat" >&nbsp;</div>',fn:function(b,a,c){b.grid[a][c]&&(b.grid[a][c].dna.jump=1,b.grid[a][c].life=900)}},{id:"life +2"}]};
U[16]={cellBg:"img/lvl5-cell-bg.png",f:120,top:0,left:0,renderer:{canvas:"canvas"},config:{depth:1,hrand:70,grid_width:4,grid_height:8,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{params:["img/wall2.png"],pos:[[0,0],[0,4],[1,2],[1,6],[2,0],[2,4],[3,2]],entity:Q},{params:[X,900],pos:[[0,7]],prop:["jumper"],entity:N},{params:["img/globul3.png",900,"occure"],pos:[[3,0]],prop:["jumper"],entity:L}],bonus:[{id:"jumper"},{id:"life +2"},{id:"kamikaze"}]};
U[17]={cellBg:"img/lvl5-cell-bg.png",f:110,top:0,left:0,renderer:{canvas:"canvas"},config:{depth:1,grid_width:4,hrand:80,grid_height:10,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{params:["img/globul3.png",8,"occure"],pos:[[0,1],[0,9],[3,0],[3,8]],prop:["jumper"],entity:L},{params:["img/wall2.png"],pos:[[0,5],[0,6],[1,2],[1,3],[1,6],[2,2],[2,5],[3,3]],entity:Q},{params:[X,10],pos:[[1,4]],prop:["jumper"],entity:N}],bonus:[{id:"jumper"},{id:"life +2"},{id:"kamikaze"}]};
U[18]={cellBg:"img/lvl5-cell-bg.png",f:120,top:0,left:0,renderer:{canvas:"canvas"},config:{depth:1,grid_width:4,grid_height:8,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{params:["img/globul3.png",5,"occure"],pos:[[0,7]],entity:L},{params:["img/cell-kami.png"],pos:[[2,2]],prop:{bonus:"kamikaze"},entity:S},{params:[X,3],pos:[[3,2]],entity:N}],bonus:[{id:"jumper"},{id:"life +2"},{id:"kamikaze"}]};
U[19]={cellBg:"img/lvl5-cell-bg.png",f:100,top:0,left:0,renderer:{canvas:"canvas"},config:{depth:1,grid_width:5,grid_height:11,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{params:["img/globul2.png",6,"occure"],pos:[[0,0],[0,1],[0,3]],entity:L},{params:["img/wall2.png"],pos:[[1,3],[1,5],[1,6],[2,2],[2,7],[3,3],[3,5],[3,7],[3,8],[4,1],[4,3],[4,7]],entity:Q},{params:[X,900],pos:[[2,5]],entity:N},{params:["img/globul.png",5,"occure"],pos:[[4,8],[4,9],[4,10]],entity:L}],bonus:[{id:"jumper"},
{id:"life +2"},{id:"kamikaze"}]};
U[20]={cellBg:"img/lvl5-cell-bg.png",f:95,top:0,left:0,renderer:{canvas:"canvas"},config:{depth:1,grid_width:6,grid_height:12,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{params:["img/wall2.png"],pos:[[1,0],[1,1],[1,2],[1,4],[2,7],[2,9],[2,10],[2,11],[4,1],[4,2],[4,4],[4,6],[4,8],[4,10],[5,0],[5,2],[5,4],[5,6],[5,8],[5,10]],entity:Q},{params:["img/globul2.png",900,"occure"],pos:[[1,5],[1,6],[1,7]],entity:L},{params:["img/cell-jump.png"],pos:[[4,0]],prop:{bonus:"jumper"},entity:S},
{params:[X,5],pos:[[5,5]],prop:["jumper"],entity:N}],bonus:[{id:"jumper"},{id:"life +2"},{id:"kamikaze"}]};
U[21]={cellBg:"img/lvl5-cell-bg.png",f:100,top:0,left:0,renderer:{canvas:"canvas"},config:{depth:1,grid_width:5,grid_height:11,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{params:["img/wall.png"],pos:[[0,0],[0,10],[1,0],[1,1],[1,3],[1,4],[1,6],[1,8],[1,9],[1,10],[2,0],[2,1],[2,2],[2,3],[2,4],[2,5],[2,6],[2,7],[2,8],[2,9],[2,10]],entity:Q},{params:[X,5],pos:[[0,3]],entity:N},{params:["img/cell-jump.png"],pos:[[1,2]],prop:{bonus:"jumper"},entity:S},{params:["img/cell-kami.png"],
pos:[[1,7]],prop:{bonus:"kamikaze"},entity:S},{params:["img/globul2.png",900,"occure"],pos:[[4,4]],prop:{bonus:"kamikaze"},entity:L}],bonus:[{id:"jumper"},{id:"life +2"},{id:"kamikaze"}]};
U[22]={cellBg:"img/lvl5-cell-bg.png",f:80,top:0,left:0,renderer:{canvas:"canvas"},config:{depth:1,hrand:80,grid_width:6,grid_height:13,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{params:["img/wall2.png"],pos:[[0,5],[0,7],[0,9],[1,5],[1,6],[1,7],[1,9],[1,10],[1,11],[1,12],[2,2],[2,3],[2,5],[2,7],[2,8],[2,11],[3,1],[3,2],[3,8],[3,9],[4,3],[4,5],[4,7]],prop:{},entity:Q},{params:["img/cell-jump.png"],pos:[[0,11],[2,4],[2,6],[3,3],[3,4],[3,7]],prop:{bonus:"jumper"},entity:S},{params:[X,
10],pos:[[1,4]],prop:{jump:0,mutable:1},entity:N},{params:[Z,6,"occure"],pos:[[3,6]],prop:{jump:0,mutable:1},entity:L}],bonus:[{id:"jumper"},{id:"life +2"},{id:"kamikaze"}]};
U[23]={cellBg:"img/lvl5-cell-bg.png",f:100,top:0,left:0,renderer:{canvas:"canvas"},config:{depth:1,grid_width:5,grid_height:11,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{params:[X,6],pos:[[0,1]],prop:{jump:0,mutable:1},entity:N},{params:["img/wall2.png"],pos:[[0,10],[1,7],[1,10],[2,7],[2,10],[3,7],[3,10],[4,7],[4,10]],prop:{},entity:Q},{params:["img/globul2.png","img/mglobul2.png",7,"occure"],pos:[[1,3]],prop:{resistance:25,bonus:"jumper"},entity:Ia}],bonus:[{id:"jumper"},
{id:"life +2"},{id:"kamikaze"}]};
U[24]={cellBg:"img/lvl5-cell-bg.png",f:86,top:0,left:0,renderer:{canvas:"canvas"},config:{depth:1,grid_width:6,grid_height:13,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{params:["img/wall2.png"],pos:[[0,0],[0,12],[1,0],[1,12],[2,0],[2,12],[3,0],[3,12],[4,0],[4,12],[5,0],[5,12]],prop:{},entity:Q},{params:[X,3],pos:[[0,1]],prop:{jump:0,mutable:1},entity:N},{params:[V,900,50],pos:[[1,3],[4,8]],prop:{},entity:R},{params:[Z,3,"occure"],pos:[[5,10]],prop:{jump:0,mutable:1},
entity:L}],bonus:[{id:"life +2"}]};
U[25]={cellBg:"img/lvl5-cell-bg.png",f:86,top:0,left:0,renderer:{canvas:"canvas"},config:{depth:1,grid_width:6,hrand:95,grid_height:13,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{params:["img/wall2.png"],pos:[[0,1],[0,9],[1,3],[1,7],[1,11],[2,1],[2,5],[2,9],[3,3],[3,7],[3,11],[4,1],[4,5],[4,9],[5,7],[5,11]],prop:{},entity:Q},{params:[X,6],pos:[[0,3]],prop:{jump:0,mutable:1},entity:N},{params:["img/cell-kami.png"],pos:[[0,5],[5,3]],prop:{bonus:"kamikaze"},entity:S},
{params:[Z,4,"occure"],pos:[[5,0]],prop:{jump:0,mutable:1},entity:L}],bonus:[{id:"jumper"},{id:"life +2"},{id:"kamikaze"}]};
U[26]={cellBg:"img/lvl5-cell-bg.png",f:100,top:0,left:0,renderer:{canvas:"canvas"},config:{depth:1,grid_width:5,grid_height:11,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{params:["img/cell-kami.png"],pos:[[0,7],[0,10]],prop:{bonus:"kamikaze"},entity:S},{params:[X,5],pos:[[0,9]],prop:{jump:0,mutable:1},entity:N},{params:["img/wall2.png"],pos:[[1,0],[1,2],[1,4],[1,6],[1,7],[1,8],[1,9],[1,10],[2,0],[2,2],[2,4],[2,5],[3,5],[3,7],[3,8]],prop:{},entity:Q},{params:["img/cell-life.png"],
pos:[[2,1],[2,3]],prop:{bonus:"life +2"},entity:S},{params:["img/cell-jump.png"],pos:[[3,0],[4,2]],prop:{bonus:"jumper"},entity:S},{params:[Z,5,"occure"],pos:[[4,0]],prop:{jump:0,mutable:1},entity:L}],bonus:[{id:"jumper"},{id:"life +2"},{id:"kamikaze"}]};
U[27]={cellBg:"img/lvl5-cell-bg.png",f:86,top:0,left:0,renderer:{canvas:"canvas"},config:{depth:1,grid_width:6,grid_height:13,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{params:[X,6],pos:[[0,1]],prop:{jump:0,mutable:1},entity:N},{params:[V,900,80],pos:[[2,6]],prop:{},entity:R},{params:[Z,5,"occure"],pos:[[5,12]],prop:{jump:0,mutable:1},entity:L}],bonus:[{id:"jumper"}]};
U[28]={cellBg:"img/lvl5-cell-bg.png",f:75,top:0,left:0,renderer:{canvas:"canvas"},config:{depth:1,grid_width:7,grid_height:15,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{params:[Z,5,"occure"],pos:[[0,2],[4,2]],prop:{jump:0,mutable:1},entity:L},{params:["img/wall2.png"],pos:[[0,3],[0,4],[0,14],[1,3],[1,4],[1,9],[1,10],[1,14],[2,3],[2,4],[2,9],[2,10],[2,14],[3,3],[3,4],[3,9],[3,10],[4,3],[4,4],[4,9],[4,10],[5,3],[5,4],[5,9],[5,10],[6,9],[6,10]],prop:{jump:0,mutable:1},
entity:Q},{params:["img/globul2.png",7,"occure"],pos:[[1,8],[5,8]],prop:{jump:0,mutable:0},entity:L},{params:["img/globul3.png",5,"occure"],pos:[[2,11],[6,11]],prop:{jump:0,mutable:0},entity:L},{params:[X,6],pos:[[3,6]],prop:{jump:0,mutable:1},entity:N}],bonus:[{id:"jumper"},{id:"life +2"},{id:"kamikaze"}]};
U[29]={cellBg:"img/lvl5-cell-bg.png",f:86,top:0,left:0,renderer:{canvas:"canvas"},config:{depth:1,grid_width:6,grid_height:13,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{params:[V,900,80],pos:[[1,1],[1,3],[1,9],[1,11],[2,4],[4,1],[4,3],[4,9],[4,11]],prop:{},entity:R},{params:["img/wall2.png"],pos:[[1,2],[1,4],[1,8],[1,10],[2,5],[2,6],[2,7],[3,2],[3,4],[3,5],[3,7],[3,8],[3,10]],prop:{},entity:Q},{params:[X,6],pos:[[2,2]],prop:{jump:0,mutable:1},entity:N},{params:[Z,
6,"occure"],pos:[[2,8]],prop:{jump:0,mutable:1},entity:L}],bonus:[{id:"jumper"},{id:"life +2"},{id:"kamikaze"}]};
U[30]={cellBg:"img/lvl30-cell-bg.png",f:75,top:0,left:0,renderer:{canvas:"canvas"},config:{depth:1,grid_width:7,grid_height:15,default_life:900,player:0,heuristic:"",players_list:[1,2]},players:[{params:["img/wall2.png"],pos:[[0,0],[0,2],[0,3],[0,4],[0,6],[0,7],[0,9],[0,11],[0,12],[0,14],[1,1],[1,2],[1,10],[1,11],[1,12],[1,14],[2,1],[2,3],[2,4],[2,9],[3,1],[3,3],[3,9],[3,10],[3,12],[3,14],[5,8],[5,10],[6,7],[6,8],[6,10],[6,11]],prop:{},entity:Q},{params:["img/cell-life.png"],pos:[[0,1],[0,
5],[0,13],[1,0],[1,13]],prop:{bonus:"life +2"},entity:S},{params:["img/globul3.png",5,"occure"],pos:[[0,10],[2,12],[2,13],[3,13],[6,0],[6,14]],prop:{jump:0,mutable:0},entity:L},{params:["img/cell-kami.png"],pos:[[2,0]],prop:{bonus:"kamikaze"},entity:S},{params:["img/globul2.png","img/mglobul2.png",6,"occure"],pos:[[2,14]],prop:{resistance:0,bonus:"jumper"},entity:P},{params:[X,5],pos:[[5,1]],prop:{jump:0,mutable:1},entity:N},{params:[Z,"img/mglobul1.png",5,"occure"],pos:[[6,9]],prop:{resistance:55,
bonus:"life +2"},entity:P}],bonus:[{id:"jumper"},{id:"life +2"},{id:"kamikaze"}]};var Qa=U.length-1;
$(document).ready(function(){function b(a,b,c){$("a.bx-next").show();$("a.bx-prev").show();2==c&&$("a.bx-next").hide();0==c&&$("a.bx-prev").hide()}gFactory=new Oa;for(var a=[],c=0;c<U.length;c++);var e;a:{for(var d,f=document.cookie.split(";"),c=0;c<f.length;c++)if(e=f[c].substr(0,f[c].indexOf("=")),d=f[c].substr(f[c].indexOf("=")+1),e=e.replace(/^\s+|\s+$/g,""),"germiz_AnonymousUser"==e){e=unescape(d);break a}e=p}if(e==p)c=1;else{var c=parseInt,g;f=e;e=ca+da;if(0==f.length)g="";else{g="undefined"==
typeof g?t:g;var j,l,n,h;d=[];var k;k=g?ja(f):f;for(var m=0;m<k.length;m+=4)j="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(k.charAt(m)),l="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(k.charAt(m+1)),f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(k.charAt(m+2)),h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(k.charAt(m+3)),n=j<<18|l<<12|f<<6|h,j=n>>>16&255,l=n>>>8&255,n&=255,d[m/
4]=String.fromCharCode(j,l,n),64==h&&(d[m/4]=String.fromCharCode(j,l)),64==f&&(d[m/4]=String.fromCharCode(j));d=d.join("");g=g?ja(d):d;g=fa(g);e=fa(ia(e).slice(0,16));d=g.length;m=g[d-1];j=g[0];for(h=2654435769*Math.floor(6+52/d);0!=h;){f=h>>>2&3;for(k=d-1;0<=k;k--)m=g[0<k?k-1:d-1],m=(m>>>5^j<<2)+(j>>>3^m<<4)^(h^j)+(e[k&3^f]^m),j=g[k]-=m;h-=2654435769}g=ga(g);g=g.replace(/\0+$/,"");g=ja(g)}c=c(g.slice(0,-5).slice(5))}for(var r=c,c=1;c<=Qa;c++)$lvlbtn=$('<a class="lvlSelect" id="lvlBtn'+c+'" href="#" rel="'+
c+'" ><span>'+c+"</span></a>"),g="none",c<r&&(g="done"),c==r&&(g="open"),$lvlbtn.addClass(g),$("#world"+(Math.floor((c-1)/15)+1)).append($lvlbtn);var G,H=t,u=t,E=new createjs.PreloadJS;E.onFileLoad=v();E.onProgress=function(){$("#ez-loader span").css("width",Math.floor(100*E.progress)+"%");1<=E.progress&&(u=q)};E.onFileProgress=v();E.onError=v();E.setMaxConnections(5);for(var B=new Pa("#world",800,600),T="img/ezelia-logo.png img/background.png img/globul1.png img/globul2.png img/cell-bg.png img/mglobul1.png img/mglobul2.png img/world1.png img/world2.png img/mglobul2.png img/buttons.png img/cadre.png img/background800x480.jpg img/bg-mutation-info.jpg img/lvlcomplete.png img/lvlloose.png audio/intro.mp3 audio/fail.mp3 audio/win.mp3 audio/mutation1.mp3 audio/popping.mp3 audio/blip.mp3 audio/bossw1.mp3 audio/lvl1.mp3 audio/intro.ogg audio/fail.ogg audio/win.ogg audio/mutation1.ogg audio/popping.ogg audio/blip.ogg audio/bossw1.ogg audio/lvl1.ogg".split(" "),
c=0;c<=Qa;c++)T.push("img/lvl"+c+"bg.png");B.da("intro",$("#intro"),function(){for(;0<T.length;){var a=T.shift();E.loadFile(a)}setTimeout(function(){u&&B.P("intro2")},1500);if(!u)var b=setInterval(function(){u&&(clearInterval(b),setTimeout(function(){B.P("intro2")},500))},200)});B.da("intro2",$("#intro2"),function(){$("#maincontrols").show();$("#maincontrols #main").hide();D.Kb.play().loop()});B.da("mainScreen",$("#mainScreen"),function(){$("#maincontrols #main").show();$("#sliderSrc").html($("#screen").html());
var a=$("#screen .slider .world").length-(Math.floor((r-1)/15)+1);0>a&&(a=0);G=$("#screen .slider:first").wb({mode:"vertical",X:t,L:t,Pb:"&nbsp;",Ub:"&nbsp;",ia:a,bb:b,bb:b});b(0,0,G.zc());$(".lvlSelect").click(function(){var a=parseInt($(this).attr("rel"));if(r<a)return t;D.Kb.stop();$("#screen").fadeOut("slow",function(){B.P("lvl"+a+"-intro");$("#mainScreen").html($("#sliderSrc").html())});return t})});for(var F,W,c=1;c<=Qa;c++)(function(b){$("#lvlcontrols").hide();var c="lvl"+b+"-intro",d=$("#lvl"+
b+"intro");0<d.length&&(d.find(".nextLvl").attr("rel","lvl"+b),B.da(c,d,function(){if(b>r)return t}),c="lvl"+b);B.da(c,$("#canvas"),function(){if(b>r)return t;$("#bgcanvas").css("background","url(img/lvl"+b+"bg.png) no-repeat");$("#levelEndModal").hide();a[b]==p&&(a[b]=gFactory.nc(U[b]));W=b;F=a[b];F.onPlayerSelect(function(a){1==a?D.Zc.play():D.tc.play()});F.onMutate(function(a,b){var c=F.F(a);c&&c instanceof N&&b&&D.Ob&&D.Ob.play()});F.onCellDie(function(a,b,c){c.Ua&&c.kamikaze&&D.uc.play()});H&&(F=gFactory.ra(F));H=t;gFactory.gb(a[b]);$("#moves").html("0");$("#lvlcontainer-id").text(b);I[b].play().loop();stats.logevent("Germiz Game","Play","Play level "+b,1);var c=b+1;$("#lvlcontrols").fadeIn("slow");gFactory.Uc(function(a,d,e){if("function"==typeof window.onGameEnd)window.onGameEnd(a,b,d,e,gFactory.Ga);F=a;gFactory.jd();$("#lvlcontrols").hide();if(e){stats.logevent("Germiz Game","LvlDone","Level cleared "+b,1);r=Math.max(r,b+1);$("#lvlBtn"+(r-1)).removeClass("open").addClass("done");
$("#lvlBtn"+r).removeClass("none").addClass("open");var f;d=ea()+r+ea();var g=ca+da;if(0==d.length)f="";else{d=fa(ia(d));1>=d.length&&(d[1]=0);for(var g=fa(ia(g).slice(0,16)),h=d.length,j=d[h-1],k=d[0],l,n=Math.floor(6+52/h),m=0;0<n--;){m+=2654435769;l=m>>>2&3;for(var u=0;u<h;u++)k=d[(u+1)%h],j=(j>>>5^k<<2)+(k>>>3^j<<4)^(m^k)+(g[u&3^l]^j),j=d[u]+=j}h=ga(d);g=[];d="";h=("undefined"==typeof f?t:f)?ia(h):h;f=h.length%3;if(0<f)for(;3>f++;)d+="=",h+="\x00";for(f=0;f<h.length;f+=3)l=h.charCodeAt(f),n=h.charCodeAt(f+
1),m=h.charCodeAt(f+2),u=l<<16|n<<8|m,l=u>>18&63,n=u>>12&63,m=u>>6&63,u&=63,g[f/3]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(l)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(n)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(m)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(u);f=g.join("");f=f.slice(0,f.length-d.length)+d}d=new Date;d.setDate(d.getDate()+365);document.cookie="germiz_AnonymousUser="+
(escape(f)+(";     expires="+d.toUTCString()))}else stats.logevent("Germiz Game","LvlDone","Level failed "+b,1);setTimeout(function(){$("#levelEndModal").show().$b();if(e){$("#levelEndModal").css("background","url('img/lvlcomplete.png') no-repeat");$("#levelEndModal").find("a.nextLvl").show();$("#levelEndModal").find("#time").html(gFactory.Ga);var d=parseInt($("#moves").text());$("#levelEndModal").find("#totalmoves").html(d);$("#levelEndModal").find("a.nextLvl").attr("rel","lvl"+c+"-intro");$("#levelEndModal").find("a.nextLvl").click(function(){D.ec.stop();
D.fail.stop();I[b].stop();var a=$(this).attr("rel");setTimeout(function(){B.P(a)},200);F.d=p;return t});I[b].stop();D.ec.play()}else $("#levelEndModal").css("background","url('img/lvlloose.png') no-repeat"),$("#levelEndModal").find("a.nextLvl").hide(),I[b].stop(),D.fail.play();$(".resetLvl").click(function(){F=gFactory.ra(a);gFactory.gb(a);$("#moves").html("0");$("#lvlcontrols").show();I[W].play().loop();return t})},2E3)})})})(c);B.da("lvl31-intro",$("#lvl31intro"));$("#reset").click(function(){alertify.confirm("这会重设当前关卡, 你确定吗 ?<br /><br />",
function(a){a==q&&(F=gFactory.ra(F),gFactory.gb(F),I[W].play().loop())});return t});$("#main").click(function(){alertify.confirm("这会重新开始游戏, 你确定吗 ?<br /><br />",function(a){a==q&&(F&&(F=gFactory.ra(F),I[W].stop()),$("#lvlcontrols").hide(),B.P("intro2"),H=q)});return t});$("#levels").click(function(){F=gFactory.ra(F);$("#lvlcontrols").hide();I[W].stop();B.P("mainScreen");return t});$("#sound").click(function(){if(oa=oa?t:q)for(var a in D)D[a].mute();else for(a in D)D[a].unmute();
oa?$("#sound").addClass("muted"):$("#sound").removeClass("muted");return t});B.P("intro")});
