var M5=M5||{};M5.Scene=function(){this.update=function(){};this.onEnter=function(){};this.onExit=function(){}};
M5.World={scenes:[],currentScene:null,update:function(a){this.currentScene&&this.currentScene.update(a)},addScene:function(a){var b=this.scenes.length;this.scenes[b]=a;return b},removeScene:function(a){return this.scenes[a]?(this.scenes[a]=null,!0):!1},showScene:function(a){return this.scenes[a]?(this.currentScene&&this.currentScene.onExit(),this.currentScene=this.scenes[a],this.currentScene.onEnter(),!0):!1}};
M5.App={WIDTH:0,HEIGHT:0,CONTAINER:null,FAST_CLICK:"ontouchstart"in document.documentElement?"touchstart":"click",TOUCH_START:"ontouchstart"in document.documentElement?"touchstart":"mousedown",TOUCH_END:"ontouchstart"in document.documentElement?"touchend":"mouseup",TOUCH_MOVE:"ontouchstart"in document.documentElement?"touchmove":"mousemove",_isInitialized:!1,_isStopped:!0,_isRunning:!1,_loopTimeout:null,_lastUpdate:null,_loop:function(){var a=M5.App;if(a._isRunning){var b=(new Date).getTime()-a._lastUpdate;
a._lastUpdate=(new Date).getTime();M5.World.update(b);a._loopTimeout=requestAnimationFrame(a._loop)}else cancelAnimationFrame(a._loopTimeout)},init:function(a){this.WIDTH=a&&a.width||320;this.HEIGHT=a&&a.height||420;this.CONTAINER=a&&a.container||document.getElementsByTagName("body")[0];this.CONTAINER.style.width=this.WIDTH+"px";this.CONTAINER.style.height=this.HEIGHT+"px";window.addEventListener("orientationchange",M5.App.onOrientationChange,!1);this._isInitialized=!0;MBP.hideUrlBar()},run:function(){if(!this._isInitialized)throw Error("M5.App needs to be initialized first. Call M5.App.init() to do so.");
this._isStopped=!1;this._isRunning=!0;this._lastUpdate=(new Date).getTime();this._loop()},stop:function(){this._isStopped=!0;this._isRunning=!1},getMouseX:function(a){var b=-1;a&&a.target&&(b=a.pageX-a.target.offsetLeft-a.target.clientLeft);return b},getMouseY:function(a){var b=-1;a&&a.target&&(b=a.pageY-a.target.offsetTop-a.target.clientTop);return b},onOrientationChange:function(){switch(window.orientation){default:case 180:case 0:document.getElementById("main_container").style.display="block";
document.getElementById("rotate_screen").style.display="none";break;case 90:case -90:document.getElementById("main_container").style.display="none",document.getElementById("rotate_screen").style.display="block"}MBP.hideUrlBar()},getVendorPrefix:function(a){function b(a,b){return b.toUpperCase()}var c=document.createElement("div"),d=["Khtml","Moz","Webkit","O","ms"],e;for(e=d.length-1;0<=e;e--)if(((d[e]?d[e]+"-":"")+a).replace(/\-(\w)/g,b)in c.style)return d[e]?"-"+d[e].toLowerCase()+"-":"";return null},
getTransitionEndEventType:function(){var a=null;switch(this.getVendorPrefix("transition")){case "-webkit-":a="webkitTransitionEnd";break;case "-o-":a="oTransitionEnd";break;default:a="transitionend"}return a}};
(function(){for(var a=0,b=["ms","moz","webkit","o"],c=0;c<b.length&&!window.requestAnimationFrame;++c)window.requestAnimationFrame=window[b[c]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[b[c]+"CancelAnimationFrame"]||window[b[c]+"RequestCancelAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(b){var c=(new Date).getTime(),f=Math.max(0,16-(c-a)),g=window.setTimeout(function(){b(c+f)},f);a=c+f;return g});window.cancelAnimationFrame||(window.cancelAnimationFrame=
function(a){clearTimeout(a)})})();Function.prototype.bind||(Function.prototype.bind=function(a){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var b=Array.prototype.slice.call(arguments,1),c=this,d=function(){},e=function(){return c.apply(this instanceof d?this:a||window,b.concat(Array.prototype.slice.call(arguments)))};d.prototype=this.prototype;e.prototype=new d;return e});
(function(a){window.MBP=window.MBP||{};MBP.viewportmeta=a.querySelector&&a.querySelector('meta[name="viewport"]');MBP.ua=navigator.userAgent;MBP.scaleFix=function(){if(MBP.viewportmeta&&/iPhone|iPad/.test(MBP.ua)&&!/Opera Mini/.test(MBP.ua)){MBP.viewportmeta.content="width=device-width, minimum-scale=1.0, maximum-scale=1.0";a.addEventListener("gesturestart",MBP.gestureStart,false)}};MBP.gestureStart=function(){MBP.viewportmeta.content="width=device-width, minimum-scale=0.25, maximum-scale=1.6"};MBP.hideUrlBar=
function(){/iPhone/.test(MBP.ua)&&!location.hash&&setTimeout(function(){pageYOffset||window.scrollTo(0,1)},1E3)};MBP.fastButton=function(a,c){this.element=a;this.handler=c;if(a.addEventListener){a.addEventListener("touchstart",this,false);a.addEventListener("click",this,false)}};MBP.fastButton.prototype.handleEvent=function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onClick(a);break;case "click":this.onClick(a)}};
MBP.fastButton.prototype.onTouchStart=function(b){b.stopPropagation();this.element.addEventListener("touchend",this,false);a.body.addEventListener("touchmove",this,false);this.startX=b.touches[0].clientX;this.startY=b.touches[0].clientY;this.element.style.backgroundColor="rgba(0,0,0,.7)"};MBP.fastButton.prototype.onTouchMove=function(a){(Math.abs(a.touches[0].clientX-this.startX)>10||Math.abs(a.touches[0].clientY-this.startY)>10)&&this.reset()};MBP.fastButton.prototype.onClick=function(a){a.stopPropagation();
this.reset();this.handler(a);a.type=="touchend"&&MBP.preventGhostClick(this.startX,this.startY);this.element.style.backgroundColor=""};MBP.fastButton.prototype.reset=function(){this.element.removeEventListener("touchend",this,false);a.body.removeEventListener("touchmove",this,false);this.element.style.backgroundColor=""};MBP.preventGhostClick=function(a,c){MBP.coords.push(a,c);window.setTimeout(function(){MBP.coords.splice(0,2)},2500)};MBP.ghostClickHandler=function(a){for(var c=0,d=MBP.coords.length;c<
d;c=c+2){var e=MBP.coords[c+1];if(Math.abs(a.clientX-MBP.coords[c])<25&&Math.abs(a.clientY-e)<25){a.stopPropagation();a.preventDefault()}}};a.addEventListener&&a.addEventListener("click",MBP.ghostClickHandler,true);MBP.coords=[];MBP.splash=function(){a.write('<link rel="apple-touch-startup-image" href="/img/'+(navigator.platform==="iPad"?"h/":"l/")+'splash.png" />')};MBP.autogrow=function(a,c){function d(){var a=this.scrollHeight;if(a>this.clientHeight)this.style.height=a+3*f+"px"}var e=c?c:12,f=
a.currentStyle?a.currentStyle.lineHeight:getComputedStyle(a,null).lineHeight,f=f.indexOf("px")==-1?e:parseInt(f,10);a.style.overflow="hidden";a.addEventListener?a.addEventListener("keyup",d,false):a.attachEvent("onkeyup",d)}})(document);
(function(){var a=false,b=/xyz/.test(function(){xyz})?/\b_super\b/:/.*/;this.Class=function(){};Class.extend=function(c){function d(){!a&&this.init&&this.init.apply(this,arguments)}var e=this.prototype;a=true;var f=new this;a=false;for(var g in c)f[g]=typeof c[g]=="function"&&typeof e[g]=="function"&&b.test(c[g])?function(a,b){return function(){var c=this._super;this._super=e[a];var d=b.apply(this,arguments);this._super=c;return d}}(g,c[g]):c[g];d.prototype=f;d.prototype.constructor=d;d.extend=arguments.callee;
return d}})();var TouchE={_$triggerElement:null,_listenerFn:null,SWIPE_UP:"up",SWIPE_RIGHT:"right",SWIPE_DOWN:"down",SWIPE_LEFT:"left",_fingerCount:0,_startX:0,_startY:0,_curX:0,_curY:0,_deltaX:0,_deltaY:0,_horzDiff:0,_vertDiff:0,_minLength:20,_swipeLength:0,_swipeAngle:null,_swipeDirection:null,init:function(a,b){this._$triggerElement=a;this._listenerFn=b},touchStart:function(a){a=a.originalEvent;a.preventDefault();a.touches?(this._fingerCount=a.touches.length,1==this._fingerCount?(this._startX=a.touches[0].pageX,
this._startY=a.touches[0].pageY):TouchE.touchCancel(a)):(this._fingerCount=1,this._startX=a.pageX,this._startY=a.pageY);this._$triggerElement.bind(M5.App.TOUCH_MOVE,function(a){TouchE.touchMove(a)})},touchMove:function(a){a=a.originalEvent;a.preventDefault();a.touches?1==a.touches.length?(this._curX=a.touches[0].pageX,this._curY=a.touches[0].pageY):TouchE.touchCancel(a):(this._curX=a.pageX,this._curY=a.pageY)},touchEnd:function(a){a=a.originalEvent;this._$triggerElement.unbind(M5.App.TOUCH_MOVE);
a.preventDefault();1==this._fingerCount&&0!=this._curX&&(this._swipeLength=Math.round(Math.sqrt(Math.pow(this._curX-this._startX,2)+Math.pow(this._curY-this._startY,2))),this._swipeLength>=this._minLength&&(this._caluculateAngle(),this._determineSwipeDirection(),this._listenerFn&&this._listenerFn(this._swipeDirection)));TouchE.touchCancel(a);this._$triggerElement.unbind(M5.App.TOUCH_MOVE)},touchCancel:function(){this._swipeLength=this._vertDiff=this._horzDiff=this._deltaY=this._deltaX=this._curY=
this._curX=this._startY=this._startX=this._fingerCount=0;this._swipeDirection=this._swipeAngle=null},_caluculateAngle:function(){var a=this._startX-this._curX,b=this._curY-this._startY;Math.round(Math.sqrt(Math.pow(a,2)+Math.pow(b,2)));a=Math.atan2(b,a);this._swipeAngle=Math.round(180*a/Math.PI);0>this._swipeAngle&&(this._swipeAngle=360-Math.abs(this._swipeAngle))},_determineSwipeDirection:function(){this._swipeDirection=45>=this._swipeAngle&&0<=this._swipeAngle?this.SWIPE_LEFT:360>=this._swipeAngle&&
315<=this._swipeAngle?this.SWIPE_LEFT:135<=this._swipeAngle&&225>=this._swipeAngle?this.SWIPE_RIGHT:45<this._swipeAngle&&135>this._swipeAngle?this.SWIPE_DOWN:this.SWIPE_UP}};var UM=UM||{};UM.States={INTRO:1,START:2,SELECT:3,LEVEL:4,CONTINUE:5};UM.G={$CONTAINER:null,STATE:UM.States.START,WIDTH:0,HEIGHT:0,currentLevel:1,highScore:0,requiredMoves:0};
UM.Main={init:function(){UM.G.STATE=UM.States.START;UM.G.WIDTH=$("#main_container").width();UM.G.HEIGHT=$("#main_container").height();UM.LevelFactory.init();UM.G.$CONTAINER=$("#game_container");M5.App.init({container:UM.G.$CONTAINER[0],width:280,height:320})},load:function(){$("#loader_screen").show();setTimeout(function(){var a=$("#loader_screen");a.transition({opacity:0},500);setTimeout(function(){a.hide();UM.Main.start()},500)},500)},start:function(){this.init();this.switchState(UM.G.STATE)},switchState:function(a){switch(a){case UM.States.START:M5.World.showScene(UM.Scenes.Start.id);
break;case UM.States.LEVEL:M5.World.showScene(UM.Scenes.Level.id);break;case UM.States.SELECT:M5.World.showScene(UM.Scenes.Select.id);break;case UM.States.CONTINUE:M5.World.showScene(UM.Scenes.Continue.id)}}};UM=UM||{};UM.Entity={};UM.Entity.Block=function(a,b){this.typeId=b||0;this.id=a;this.yPos=this.xPos=0;this.$node=null;this.init(a)};
UM.Entity.Block.prototype={init:function(a){this.yPos=~~(a/UM.Scenes.Level.FIELD_WIDTH);this.xPos=a-this.yPos*UM.Scenes.Level.FIELD_WIDTH;a=$(document.createElement("div"));a.css("width",UM.Scenes.Level.CELL_PIXEL_DIMENSION+"px");a.css("height",UM.Scenes.Level.CELL_PIXEL_DIMENSION+"px");a.css("left",this.xPos*UM.Scenes.Level.CELL_PIXEL_DIMENSION+"px");a.css("top",this.yPos*UM.Scenes.Level.CELL_PIXEL_DIMENSION+"px");a.css("position","absolute");a.addClass("block");4==this.typeId?a.addClass("lava"):
a.addClass("grey");this.$node=a}};UM.Entity.Mover=function(a,b){this.id=a;this.typeId=b;this.yPos=this.xPos=0;this.$node=null;this.moveDuration=500;this.isActive=!0;this.init(a)};
UM.Entity.Mover.prototype={init:function(a){this.yPos=~~(a/UM.Scenes.Level.FIELD_WIDTH);this.xPos=a-this.yPos*UM.Scenes.Level.FIELD_WIDTH;a=$(document.createElement("div"));a.attr("id","mover_"+this.id);a.attr("data-type","mover");a.attr("data-mover_id",this.id);a.css("width",UM.Scenes.Level.CELL_PIXEL_DIMENSION+"px");a.css("height",UM.Scenes.Level.CELL_PIXEL_DIMENSION+"px");a.css("left",this.xPos*UM.Scenes.Level.CELL_PIXEL_DIMENSION+"px");a.css("top",this.yPos*UM.Scenes.Level.CELL_PIXEL_DIMENSION+
"px");a.css("position","absolute");a.addClass("block");switch(this.typeId){case 8:a.addClass("purple");break;case 7:a.addClass("green");break;default:case 6:a.addClass("yellow")}this.$node=a},move:function(a){var b=this,c=0,d=!1;UM.Scenes.Level._data[b.xPos+b.yPos*UM.Scenes.Level.FIELD_WIDTH]=0;switch(a){case TouchE.SWIPE_UP:c=UM.Scenes.Level.getFreeUpperFields(b.xPos,b.yPos);b.updatePosition(b.xPos,b.yPos-c);b.$node.transition({top:"-="+c*UM.Scenes.Level.CELL_PIXEL_DIMENSION},b.moveDuration);break;
case TouchE.SWIPE_RIGHT:c=UM.Scenes.Level.getFreeRightFields(b.xPos,b.yPos);b.updatePosition(b.xPos+c,b.yPos);b.$node.transition({left:"+="+c*UM.Scenes.Level.CELL_PIXEL_DIMENSION},b.moveDuration);break;case TouchE.SWIPE_DOWN:c=UM.Scenes.Level.getFreeBelowFields(b.xPos,b.yPos);b.updatePosition(b.xPos,b.yPos+c);b.$node.transition({top:"+="+c*UM.Scenes.Level.CELL_PIXEL_DIMENSION},b.moveDuration);break;case TouchE.SWIPE_LEFT:c=UM.Scenes.Level.getFreeLeftFields(b.xPos,b.yPos),b.updatePosition(b.xPos-c,
b.yPos),b.$node.transition({left:"-="+c*UM.Scenes.Level.CELL_PIXEL_DIMENSION},b.moveDuration)}0<c&&(d=UM.Scenes.Level._isMoving=!0,setTimeout(function(){if(UM.Scenes.Level.isMoverDead(b,a))b.remove(),UM.Scenes.Level.setPositionValue(b.xPos,b.yPos,0),setTimeout(function(){UM.Main.switchState(UM.States.LEVEL)},500);else{var c=UM.Scenes.Level.removeNeighbours(b);if(0<c.length){c.push(b);for(var d=0;d<c.length;d++)c[d].remove(),UM.Scenes.Level.setPositionValue(c[d].xPos,c[d].yPos,0);0==UM.Scenes.Level.getMoversLeft()&&
setTimeout(function(){UM.Scenes.Level.nextLevel()},500)}}UM.Scenes.Level._isMoving=!1},b.moveDuration));return d},updatePosition:function(a,b){this.xPos=a;this.yPos=b;UM.Scenes.Level._data[this.xPos+this.yPos*UM.Scenes.Level.FIELD_WIDTH]=this.typeId},updatePositionByPixels:function(){this.xPos=~~(parseInt(this.$node.css("left"))/UM.Scenes.Level.CELL_PIXEL_DIMENSION);this.yPos=~~(parseInt(this.$node.css("top"))/UM.Scenes.Level.CELL_PIXEL_DIMENSION);UM.Scenes.Level._data[this.xPos+this.yPos*UM.Scenes.Level.FIELD_WIDTH]=
this.typeId},remove:function(){var a=$("#mover_"+this.id);this.isActive=!1;a.transition({opacity:0,rotate:"45deg",scale:1.6},500);setTimeout(function(){a.remove()},500)}};UM=UM||{};
UM.LevelFactory={KEY_SAVE_DATA:"unitem-save-data",_datas:[],_savedData:{},init:function(){try{this._loadSavedData()}catch(a){this._savedData={}}this._datas[0]={possibleSteps:1,data:[3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,6,0,0,0,6,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3]};this._datas[1]={possibleSteps:5,data:[3,3,3,3,3,3,3,3,7,3,0,0,0,3,3,0,3,0,3,0,3,3,0,3,0,3,0,3,3,0,3,0,3,0,3,3,0,3,0,3,0,3,3,0,0,0,3,7,3,3,3,3,3,3,3,3]};this._datas[2]={possibleSteps:5,data:[3,3,3,3,3,3,3,3,
0,0,0,0,0,3,3,0,0,0,0,0,3,4,0,0,0,0,8,3,3,0,0,0,0,3,3,4,0,0,0,0,8,3,3,3,0,0,0,0,3,3,3,3,3,3,3,3]};this._datas[3]={possibleSteps:1,data:[3,3,3,3,3,3,3,3,3,6,0,6,3,3,3,3,3,0,3,3,3,3,3,3,0,3,3,3,3,3,3,0,3,3,3,3,3,3,0,3,3,3,3,3,3,6,3,3,3,3,3,3,3,3,3,3]};this._datas[4]={possibleSteps:4,data:[4,4,4,4,4,3,4,4,6,0,6,0,0,4,4,0,0,0,0,0,4,4,0,0,0,7,0,4,4,0,0,0,0,0,4,4,0,0,0,0,7,4,4,0,0,0,0,0,4,4,4,4,4,4,4,4]};this._datas[5]={possibleSteps:5,data:[3,3,3,3,3,3,3,3,6,0,6,0,6,3,3,0,0,0,0,0,3,3,0,0,0,0,0,3,3,0,0,
0,0,0,3,3,0,0,0,0,0,3,3,3,3,3,0,0,3,3,3,3,3,3,3,3]};this._datas[6]={possibleSteps:7,data:[3,3,3,3,3,3,3,3,6,0,6,0,0,3,3,0,7,0,0,6,3,3,0,0,0,0,0,3,3,0,0,8,0,0,3,3,0,0,0,0,0,3,3,8,0,0,7,0,3,3,3,3,3,3,3,3]};this._datas[7]={possibleSteps:6,data:[3,3,3,3,3,3,3,4,0,6,0,0,7,4,4,0,0,0,0,0,4,4,0,0,8,0,0,4,4,0,8,0,0,0,4,4,0,0,0,0,0,4,4,0,7,0,0,6,4,3,3,3,3,3,3,3]};this._datas[8]={possibleSteps:6,data:[3,3,3,3,3,3,3,3,0,0,0,7,0,3,3,6,0,0,0,7,3,3,0,3,3,3,3,3,3,0,0,3,7,0,3,3,0,0,0,0,0,3,3,6,0,0,3,0,3,3,3,3,3,3,
3,3]};this._datas[9]={possibleSteps:10,data:[3,3,3,3,3,3,3,3,6,0,0,8,6,3,3,0,0,0,0,0,3,3,0,0,3,0,0,3,3,0,0,0,3,0,3,3,0,0,0,0,0,3,3,8,0,0,6,0,3,3,3,3,3,3,3,3]};this._datas[10]={possibleSteps:32,data:[3,3,3,3,3,3,3,3,8,0,6,0,0,3,3,0,0,0,0,0,3,3,8,3,3,3,0,3,3,0,3,3,3,0,3,3,0,0,7,0,7,3,3,8,0,6,7,6,3,3,3,3,3,3,3,3]};this._datas[11]={possibleSteps:9,data:[3,3,3,3,3,3,3,3,3,3,3,3,7,3,3,3,3,3,3,6,3,3,3,3,3,7,0,3,3,3,3,8,0,0,3,3,8,7,0,0,0,3,3,6,0,0,0,8,3,3,3,3,3,3,3,3]};this._datas[12]={possibleSteps:16,data:[3,
3,3,3,3,3,3,3,7,3,7,3,6,3,3,8,0,8,0,0,3,3,3,3,0,3,6,3,3,3,3,0,3,0,3,3,0,0,0,3,0,3,3,0,0,0,0,0,3,3,4,3,4,3,3,3]};this._datas[13]={possibleSteps:24,data:[3,3,3,3,3,3,3,4,0,0,0,7,0,4,4,0,0,7,0,8,4,4,6,0,0,0,0,4,4,0,0,6,0,0,4,4,6,0,0,0,0,4,4,8,0,0,7,0,4,3,3,3,3,3,3,3]};this._datas[14]={possibleSteps:8,data:[3,4,3,4,4,4,3,4,8,0,7,0,8,4,4,0,0,0,0,0,4,4,0,6,0,0,8,4,4,0,0,6,0,0,4,4,0,7,0,0,0,4,4,0,0,8,0,8,4,3,4,4,4,4,4,3]};this._datas[15]={possibleSteps:18,data:[3,3,3,3,3,3,3,3,8,0,7,0,8,3,3,0,0,0,0,0,3,
3,0,6,7,0,8,3,3,0,0,6,0,0,3,3,0,7,0,0,0,3,3,0,0,8,0,8,3,3,3,3,3,3,3,3]}},getLevel:function(a){a-=1;return this._datas[a]?this._datas[a]:null},isPlayable:function(a){a-=1;return 0==a?!0:this._savedData.hasOwnProperty(a-1)},isLastLevel:function(){return this._datas.length<UM.G.currentLevel},updateSaveData:function(a,b){var c=a-1;if(!this._savedData||!this._savedData[c]||this._savedData[c]>b){this._savedData[c]=b;try{this.save()}catch(d){}}},getRatingCss:function(a,b){var c=a-1,d="rating_none",e=b||
this._savedData[c]||1E3;this._savedData&&this._savedData[c]&&(c=this.getLevel(a).possibleSteps,c>=e?d="rating_three":c+2>=e?d="rating_two":c+4>=e&&(d="rating_one"));return d},getLevelState:function(a){var b=a-1;return!this._savedData.hasOwnProperty(b)&&!this.isPlayable(a)?"locked":this._savedData.hasOwnProperty(b)?"solved":"unlocked"},_loadSavedData:function(){var a=UM.LevelFactory.KEY_SAVE_DATA,b={};window.localStorage?this._savedData=JSON.parse(localStorage.getItem(a)):(b=document.cookie,b=-1!=
b.indexOf(a)?(b=b.split(a+"=")[1])?JSON.parse(b.split(";")[0]):{}:{},this._savedData=b);this._savedData||(this._savedData={})},save:function(){var a=UM.LevelFactory.KEY_SAVE_DATA,b=JSON.stringify(this._savedData);if(window.localStorage)localStorage.setItem(a,b);else{var c;c=new Date;c.setTime(c.getTime()+31536E6);c="; expires="+c.toGMTString();document.cookie=a+"="+b+c+"; path=/"}}};UM=UM||{};UM.Scenes={};UM.Scenes.Start=new M5.Scene;UM.Scenes.Start.id=M5.World.addScene(UM.Scenes.Start);UM.Scenes.Start._$node=null;
UM.Scenes.Start.onEnter=function(){
	this._$node=$("#start_screen");this._$node.show();this._$node.find("div.button").css("opacity",0);
	var a=0,b=$(this._$node.find("#logo_background")),c=$(this._$node.find("#logo_text"));b.css("opacity",0).css("left",-320);
	c.css("opacity",0).css("left",320);b.transition({opacity:100,left:"0"},500);c.transition({opacity:100,left:"0"},500);
	this._$node.find("div.button").each(function(b,c){var f=$(c),g=~~((UM.Scenes.Start._$node.width()-f.width())/2),h=240+65*b,i=h-10;
f.css("left",g+"px").end();f.css("top",h+"px").end();setTimeout(function(){f.transition({opacity:100,top:i},500)},a);a+=100});
	this._$node.delegate("div.button",M5.App.FAST_CLICK,UM.Scenes.Start.onButtonClick)};UM.Scenes.Start.update=function(){};UM.Scenes.Start.onExit=function(){this._$node.hide();this._$node.undelegate("div.button",M5.App.TOUCH_START)};
UM.Scenes.Start.onButtonClick=function(){switch($(this).attr("data-action")){case "play":UM.Scenes.Start._$node.find("#logo_background").transition({opacity:0,left:"-=320"},500);UM.Scenes.Start._$node.find("#logo_text").transition({opacity:100,left:"+=320"},500);var a=0;$(UM.Scenes.Start._$node.find("div.button").toArray().reverse()).each(function(b,c){var d=$(c);setTimeout(function(){d.transition({opacity:0,top:"+=10"},500)},a);a+=100});a+=500;setTimeout(function(){UM.Main.switchState(UM.States.SELECT)},
a);break;case "more":"function"==typeof showLeadBoltWall&&showLeadBoltWall()}};UM.Scenes.Select=new M5.Scene;UM.Scenes.Select.id=M5.World.addScene(UM.Scenes.Select);UM.Scenes.Select._$node=null;UM.Scenes.Select._levelScroll=null;
UM.Scenes.Select.onEnter=function(){this._$node=$("#select_screen");this._$node.css("left",UM.G.WIDTH+"px");this._$node.css("opacity","0");this._$node.find("ul").empty();for(var a=$(this._$node.find("ul")),b=0;b<UM.LevelFactory._datas.length;b++){var c=UM.LevelFactory.isPlayable(b+1)?"yes":"no",d="yes"==c?"":"strike",e='<span class="level_rating '+UM.LevelFactory.getRatingCss(b+1)+'" style="padding-right: 5px"></span>',f='<span class="level_state '+UM.LevelFactory.getLevelState(b+1)+'"></span>';a.append('<li data-playable="'+
c+'" data-level="'+(b+1)+'">'+(e+'<span class="'+d+'">关卡 '+(b+1)+"</span>"+f)+"</li>")}this._levelScroll=new iScroll("level_list");setTimeout(function(){this._levelScroll.refresh()}.bind(this),50);this._$node.delegate("li[data-level]","click",UM.Scenes.Select.onLevelSelect);a=$(this._$node.find("div.button_small[data-action=back]")[0]);b=~~((UM.G.WIDTH-a.width())/2);a.css("top",360).css("left",b);this._$node.delegate("div.button_small[data-action=back]","click",UM.Scenes.Select.onBackSelect);this._$node.show();
this._$node.transition({opacity:100,left:0},500)};UM.Scenes.Select.onBackSelect=function(a){a.preventDefault();UM.Scenes.Select._$node.transition({opacity:0,left:-1*UM.G.WIDTH},500);setTimeout(function(){UM.Main.switchState(UM.States.START)},500)};UM.Scenes.Select.update=function(){};
UM.Scenes.Select.onLevelSelect=function(){if("no"!=$(this).attr("data-playable")){var a=~~$(this).attr("data-level");UM.G.currentLevel=a;UM.Scenes.Select._$node.transition({opacity:0,left:-1*UM.G.WIDTH},500);setTimeout(function(){UM.Main.switchState(UM.States.LEVEL)},500)}};UM.Scenes.Select.onExit=function(){this._$node.hide();this._$node.undelegate("div.button_small[data-action=back]","click");this._levelScroll.destroy();this._$node=this._levelScroll=null};UM.Scenes.Level=new M5.Scene;
UM.Scenes.Level.id=M5.World.addScene(UM.Scenes.Level);UM.Scenes.Level._$node=null;UM.Scenes.Level._movers=[];UM.Scenes.Level._blocks=[];UM.Scenes.Level._data=[];UM.Scenes.Level._possibleSteps=0;UM.Scenes.Level._currentMover=null;UM.Scenes.Level._isMoving=!1;UM.Scenes.Level.CELL_PIXEL_DIMENSION=40;UM.Scenes.Level.FIELD_WIDTH=7;UM.Scenes.Level.FIELD_HEIGHT=8;
UM.Scenes.Level.onEnter=function(){this._$node=$("#game_screen");var a=UM.LevelFactory.getLevel(UM.G.currentLevel);a&&(this._possibleSteps=a.possibleSteps,this._data=a.data.slice());this._currentMover=null;this._isMoving=!1;this._movers=[];this._blocks=[];this.create();this.show();this.setListeners();$("#game_container").show();this._$node.css("left",UM.G.WIDTH+"px");this._$node.css("opacity","0");var a=$(this._$node.find("div.button_small")[0]),b=$(this._$node.find("div.button_small")[1]),c=$($("#pause_screen").find("div.button_small")[0]),
d=$($("#pause_screen").find("div.button_small")[1]);a.css("top",352).css("left","20px");b.css("top",352).css("left","165px");c.css("top",200).css("left",15);d.css("top",200).css("left",165);this._$node.delegate("div.button_small[data-action=restart]","click",UM.Scenes.Level.onRestartSelect);this._$node.delegate("div.button_small[data-action=pause]","click",UM.Scenes.Level.onPauseSelect);$("#pause_screen").delegate("div.button_small[data-action=main]","click",UM.Scenes.Level.onMainSelect);$("#pause_screen").delegate("div.button_small[data-action=resume]",
"click",UM.Scenes.Level.onResumeSelect);this._$node.show();this._$node.transition({opacity:100,left:0},500)};UM.Scenes.Level.onRestartSelect=function(a){a.preventDefault();UM.Main.switchState(UM.States.LEVEL)};UM.Scenes.Level.onPauseSelect=function(a){a.preventDefault();UM.Scenes.Level._$node.hide();$("#pause_screen").show()};UM.Scenes.Level.onMainSelect=function(a){a.preventDefault();UM.Main.switchState(UM.States.START)};
UM.Scenes.Level.onResumeSelect=function(a){a.preventDefault();$("#pause_screen").hide();UM.Scenes.Level._$node.show()};UM.Scenes.Level.getFreeRightFields=function(a,b){for(var c=0,d=a+1;d<this.FIELD_WIDTH;){if(0==this._data[b*this.FIELD_WIDTH+d])c++;else break;d++}return c};UM.Scenes.Level.getFreeLeftFields=function(a,b){for(var c=0,d=a-1;-1<d;d--)if(0==this._data[b*this.FIELD_WIDTH+d])c++;else break;return c};
UM.Scenes.Level.getFreeUpperFields=function(a,b){for(var c=0,d=b-1;-1<d;){if(0==this._data[d*this.FIELD_WIDTH+a])c++;else break;d--}return c};UM.Scenes.Level.getFreeBelowFields=function(a,b){for(var c=0,d=b+1;d<this.FIELD_HEIGHT;){if(0==this._data[d*this.FIELD_WIDTH+a])c++;else break;d++}return c};
UM.Scenes.Level.onExit=function(){$("#pause_screen").hide();UM.Scenes.Level._$node.hide();$("#pause_screen").undelegate();this._$node.undelegate();this.removeListeners();$("#game_container").hide();UM.G.$CONTAINER.empty();this._data=[]};
UM.Scenes.Level.create=function(){this._movers=[];this._blocks=[];for(var a=UM.G.requiredMoves=0;a<this._data.length;a++)if(5<this._data[a])this._movers.push(new UM.Entity.Mover(a,this._data[a]));else if(3==this._data[a]){var b=new UM.Entity.Block(a);this._blocks.push(b)}else 4==this._data[a]&&(b=new UM.Entity.Block(a,4),this._blocks.push(b))};UM.Scenes.Level.show=function(){for(var a=0;a<this._blocks.length;a++)UM.G.$CONTAINER.append(this._blocks[a].$node);for(a=0;a<this._movers.length;a++)UM.G.$CONTAINER.append(this._movers[a].$node)};
UM.Scenes.Level.getMoverById=function(a){for(var b=null,c=0;c<this._movers.length;c++)if(this._movers[c].id==a){b=this._movers[c];break}return b};UM.Scenes.Level.getMoverByPosition=function(a,b){for(var c=null,d=0;d<this._movers.length;d++)if(this._movers[d].xPos==a&&this._movers[d].yPos==b&&!0==this._movers[d].isActive){c=this._movers[d];break}return c};UM.Scenes.Level.isMoverOnPosition=function(a,b){return 5<this._data[a+b*this.FIELD_WIDTH]};
UM.Scenes.Level.isSameMoverOnPosition=function(a,b,c){return this._data[a+b*this.FIELD_WIDTH]==c};UM.Scenes.Level.setPositionValue=function(a,b,c){this._data[a+b*this.FIELD_WIDTH]=c};
UM.Scenes.Level.isMoverDead=function(a,b){return a.xPos<this.FIELD_WIDTH-1&&b==TouchE.SWIPE_RIGHT&&4==this._data[a.xPos+1+a.yPos*this.FIELD_WIDTH]||0<a.xPos&&b==TouchE.SWIPE_LEFT&&4==this._data[a.xPos-1+a.yPos*this.FIELD_WIDTH]||a.yPos<this.FIELD_HEIGHT-1&&b==TouchE.SWIPE_DOWN&&4==this._data[a.xPos+(a.yPos+1)*this.FIELD_WIDTH]||0<a.yPos&&b==TouchE.SWIPE_UP&&4==this._data[a.xPos+(a.yPos-1)*this.FIELD_WIDTH]?!0:!1};
UM.Scenes.Level.removeNeighbours=function(a){var b=[];a.xPos<this.FIELD_WIDTH-1&&this.isSameMoverOnPosition(a.xPos+1,a.yPos,a.typeId)&&b.push(this.getMoverByPosition(a.xPos+1,a.yPos));0<a.xPos&&this.isSameMoverOnPosition(a.xPos-1,a.yPos,a.typeId)&&b.push(this.getMoverByPosition(a.xPos-1,a.yPos));a.yPos<this.FIELD_HEIGHT-1&&this.isSameMoverOnPosition(a.xPos,a.yPos+1,a.typeId)&&b.push(this.getMoverByPosition(a.xPos,a.yPos+1));0<a.yPos&&this.isSameMoverOnPosition(a.xPos,a.yPos-1,a.typeId)&&b.push(this.getMoverByPosition(a.xPos,
a.yPos-1));return b};UM.Scenes.Level.getMoversLeft=function(){for(var a=0,b=0;b<this._data.length;b++)5<this._data[b]&&a++;return a};UM.Scenes.Level.update=function(){};
UM.Scenes.Level.setListeners=function(){TouchE.init(UM.G.$CONTAINER,function(a){null!=UM.Scenes.Level._currentMover&&!UM.Scenes.Level._isMoving&&UM.Scenes.Level._currentMover.move(a)&&UM.G.requiredMoves++;UM.Scenes.Level._currentMover=null}.bind(this));UM.G.$CONTAINER.bind(M5.App.TOUCH_START,function(a){TouchE.touchStart(a,"game_container")});UM.G.$CONTAINER.bind(M5.App.TOUCH_END,function(a){TouchE.touchEnd(a)});UM.G.$CONTAINER.delegate("div[data-type=mover]",M5.App.TOUCH_START,function(){UM.Scenes.Level._currentMover=
UM.Scenes.Level.getMoverById(~~$(this).attr("data-mover_id"))})};UM.Scenes.Level.removeListeners=function(){UM.G.$CONTAINER.unbind(M5.App.TOUCH_START);UM.G.$CONTAINER.unbind(M5.App.TOUCH_END);UM.G.$CONTAINER.undelegate("div[data-type=mover]",M5.App.TOUCH_START)};
UM.Scenes.Level.nextLevel=function(){UM.LevelFactory.updateSaveData(UM.G.currentLevel,UM.G.requiredMoves);UM.G.currentLevel++;UM.Scenes.Level._$node.transition({opacity:0,left:-1*UM.G.WIDTH},500);setTimeout(function(){UM.Main.switchState(UM.States.CONTINUE)},500)};UM.Scenes.Continue=new M5.Scene;UM.Scenes.Continue.id=M5.World.addScene(UM.Scenes.Continue);UM.Scenes.Continue._$node=null;
UM.Scenes.Continue.onEnter=function(){this._$node=$("#continue_screen");this._$node.css("left",UM.G.WIDTH+"px");this._$node.css("opacity","0");this._$node.find('div.button_small[data-action="main"]').css("top",240);this._$node.find('div.button_small[data-action="main"]').css("left",15);this._$node.find('div.button_small[data-action="next"]').css("top",240);this._$node.find('div.button_small[data-action="next"]').css("left",165);UM.LevelFactory.isLastLevel()?this._$node.find('div.button_small[data-action="next"]').addClass("strike"):
this._$node.find('div.button_small[data-action="next"]').removeClass("strike");this._$node.find("#required_moves").text(UM.G.requiredMoves);this._$node.find(".level_rating").removeClass("rating_three rating_two rating_one");this._$node.find(".level_rating").addClass(UM.LevelFactory.getRatingCss(UM.G.currentLevel-1,UM.G.requiredMoves));this._$node.show();this._$node.transition({opacity:100,left:0},500);"function"==typeof BOOSTERMEDIA_LEVELCOMPLETE&&BOOSTERMEDIA_LEVELCOMPLETE();this._$node.delegate("div.button_small",
M5.App.FAST_CLICK,UM.Scenes.Continue.onButtonClick)};UM.Scenes.Continue.onButtonClick=function(){if(!$(this).hasClass("strike")){UM.Scenes.Continue._$node.transition({opacity:0,left:-1*UM.G.WIDTH},500);var a=null;switch($(this).attr("data-action")){case "next":a=UM.States.LEVEL;break;case "main":a=UM.States.START}setTimeout(function(){UM.Main.switchState(a)},500)}};UM.Scenes.Continue.update=function(){};UM.Scenes.Continue.onExit=function(){this._$node.hide();this._$node.undelegate("div.button",M5.App.FAST_CLICK)};
