var d=void 0,n={h:-2,j:-1,g:0,i:1,c:2,a:3,b:4,e:5,d:6,f:42},q=d,r,s,t,u=0;function v(a){this.player=a;this.life=q.default_life;this.infectable=!0;this.master=!1}function Node(a,f,e,c,g,b,k,h){this.parent=a;this.grid=f;this.player=e;this.children=c;this.point={x1:g,y1:b,x2:k,y2:h}}
onmessage=function(a){switch(a.data.action){case "move":s=a.data.grid;r=a.data.ptype;t=a.data.players_list;q.heuristic=q.heuristic||a.data.heuristic;var f=(new Date).getTime(),e=new Node(null,s,q.player,[]);a=d;var c=[],g=-99999;e.children=w(e);for(var b,k=0,h=0;h<q.grid_width;h++)for(b=0;b<q.grid_height;b++)s[h][b]==d||s[h][b].player==d||s[h][b].type==n.a&&k++;b=k;k=q.depth;h=10>b?1:2;x=3>b?0:10>b&&64<q.grid_height*q.grid_width?0:q.hrand;for(b=0;b<e.children.length;b+=h){var j=y(e.children[b],k,
-99999,99999);j>g?(g=j,a=e.children[b],c=[],c.push(a)):j==g&&c.push(e.children[b]);if((new Date).getTime()-f>=z)break}(f=c[Math.floor(Math.random()*(c.length-1-0+1)+0)])&&(2>Math.abs(f.point.x1-f.point.x2)&&2>Math.abs(f.point.y1-f.point.y2))&&(a=f);f={type:"move"};f.move=a?a.point:d;f.ptype=r;f.player=q.player;postMessage(f);break;case "init":q=a.data.config,q.hrand=q.hrand||50,q.player=a.data.player,q.grid_width=q.grid_width,q.grid_height=q.grid_height,q.depth=q.depth,q.heuristic=q.heuristic,q.default_life=
q.default_life}};var A=!1;
function B(a,f,e,c,g,b,k,h){if(a.grid[g][b]&&a.grid[g][b].k)return null;for(var j=[],l=0;l<q.grid_width;l++)j[l]=[];for(l=0;l<q.grid_width;l++)for(var m=0;m<q.grid_height;m++)a.grid[l][m]!=d&&(j[l][m]=JSON.parse(JSON.stringify(a.grid[l][m])),j[l][m].life=a.grid[l][m].life-1,0>=j[l][m].life&&-99<=j[l][m].life&&(j[l][m]=d));j[g][b]=new v(a.player);j[g][b].type=h;k&&(j[e][c]==d&&!A&&(A=!0),j[e][c]=d);k=a.player;h=C[b%2];for(l=0;l<h.length;l++){var p=h[l],m=g+p[0],p=b+p[1];0<=m&&(m<q.grid_width&&0<=p&&
p<q.grid_height&&j[m][p]!=d&&j[m][p].infectable)&&(j[m][p]=new v(k),j[m][p].type=j[g][b].type)}return new Node(a,j,f,[],e,c,g,b)}var C=[[[0,-2],[1,-1],[1,1],[0,2],[0,1],[0,-1]],[[0,-2],[0,-1],[0,1],[0,2],[-1,1],[-1,-1]]];dirs_l2=[[[0,-4],[1,-3],[1,-2],[1,0],[1,2],[1,3],[0,4],[0,3],[-1,2],[-1,0],[-1,-2],[0,-3]],[[0,-4],[-1,-3],[1,-2],[1,0],[1,2],[-1,3],[0,4],[0,3],[-1,2],[-1,0],[-1,-2],[0,-3]]];
function w(a){a.grid=a.grid;a.player=a.player;a.parent=a.parent;a.children=a.children;a.point=a.point;for(var f=[],e=0;e<q.grid_width;e++)for(var c=0;c<q.grid_height;c++)if(a.grid[e][c]!=d&&a.grid[e][c].player==a.player){var g;g=a.player;for(var b=0;b<t.length;b++)if(t[b]==g){u=b;break}u++;u%=t.length;g=t[u];for(var b=C[c%2],k=0;k<b.length;k++){var h=b[k],j=e+h[0],h=c+h[1];0<=j&&(j<q.grid_width&&0<=h&&h<q.grid_height&&s[j][h]==d)&&f.push(B(a,g,e,c,j,h,!1,a.grid[e][c].type))}if(a.grid[e][c]&&a.grid[e][c].dna&&
0<a.grid[e][c].dna.jump){b=dirs_l2[c%2];for(k=0;k<b.length;k++)h=b[k],j=e+h[0],h=c+h[1],0<=j&&(j<q.grid_width&&0<=h&&h<q.grid_height&&s[j][h]==d)&&f.push(B(a,g,e,c,j,h,!0,a.grid[e][c].type))}}return f}var z=3E3,x=0,D=1E3;function y(a,f,e,c){var g=(new Date).getTime();a.children=w(a);if(0==a.children.length||0==f)return E(a);for(var b=0;b<a.children.length;b+=2){e=Math.max(e,F(a.children[b],f-1,e,c));if(e>=c)return e;if((new Date).getTime()-g>=D)break}a.children.length=0;return e}var G=1E3;
function F(a,f,e,c){var g=(new Date).getTime()-NaN;a.children=w(a);if(0==a.children.length||0==f)return E(a);for(var b=0;b<a.children.length;b++){c=Math.min(c,y(a.children[b],f-1,e,c));if(c<=e)return c;g=(new Date).getTime()-NaN;if(g>=G)break}a.children.length=0;return c}var H={};H.random=I;H.occure=J;function E(a){var f=x;return f&&Math.floor(100*Math.random()+1)<f?I():H[q.heuristic](a)}function I(){return Math.random()}var n={h:-2,j:-1,g:0,i:1,c:2,a:3,b:4,e:5,d:6,f:42},K=[n.c,n.a,n.b,n.e,n.d];
function J(a){for(var f=0,e=0,c=0;c<q.grid_width;c++)for(var g=0;g<q.grid_height;g++)a.grid[c][g]!=d&&!(0>K.indexOf(a.grid[c][g].type))&&(a.grid[c][g].player==q.player?f++:e++);return f-e};
