var imglib = [
{
	"sheetname"				: "playersheet",
	"type"					: "player",
	"src"					: "library/playersheet.gif",
	"width"					: 144,
	"height"				: 48,
	"framewidth"			: 48,
	"frameheight"			: 48,
	"framedelay"			: 2,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "choppersheet",
	"type"					: "chopper",
	"src"					: "library/choppersheet.png",
	"width"					: 128,
	"height"				: 64,
	"framewidth"			: 64,
	"frameheight"			: 64,
	"framedelay"			: 1,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "carsheet",
	"type"					: "car",
	"src"					: "library/carsheet.gif",
	"width"					: 96,
	"height"				: 240,
	"framewidth"			: 48,
	"frameheight"			: 48,
	"framedelay"			: 2,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "alertsheet",
	"type"					: "alerter",
	"src"					: "library/alert.gif",
	"width"					: 64,
	"height"				: 32,
	"framewidth"			: 32,
	"frameheight"			: 32,
	"framedelay"			: 4,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "spycarsheet",
	"type"					: "spycar",
	"src"					: "library/spycar.gif",
	"width"					: 96,
	"height"				: 48,
	"framewidth"			: 48,
	"frameheight"			: 48,
	"framedelay"			: 2,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "playershadow",
	"type"					: "playershadow",
	"src"					: "library/playershadow.png",
	"width"					: 96,
	"height"				: 48,
	"framewidth"			: 48,
	"frameheight"			: 48,
	"framedelay"			: 1,
	"framesperdirection"	: 1,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "numberssheet",
	"type"					: "numbers",
	"src"					: "library/numbers.png",
	"width"					: 240,
	"height"				: 48,
	"framewidth"			: 24,
	"frameheight"			: 48,
	"framedelay"			: 0,
	"framesperdirection"	: 0,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "explosionsheet",
	"type"					: "explosion",
	"src"					: "library/explosion.png",
	"width"					: 288,
	"height"				: 48,
	"framewidth"			: 48,
	"frameheight"			: 48,
	"framedelay"			: 4,
	"framesperdirection"	: 5,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "playermissilesheet",
	"type"					: "playermissile",
	"src"					: "library/playermissile.png",
	"width"					: 8,
	"height"				: 32,
	"framewidth"			: 8,
	"frameheight"			: 16,
	"framedelay"			: 0,
	"framesperdirection"	: 1,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "entitysheet",
	"type"					: "entity",
	"src"					: "library/entities.png",
	"width"					: 64,
	"height"				: 224,
	"framewidth"			: 32,
	"frameheight"			: 32,
	"framedelay"			: 4,
	"framesperdirection"	: 2,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "tilesheet",
	"type"					: "tile",
	"src"					: "library/tilesheet.gif",
	"width"					: 48,
	"height"				: 48,
	"framewidth"			: 48,
	"frameheight"			: 48,
	"framedelay"			: 4,
	"framesperdirection"	: 1,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
},
{
	"sheetname"				: "markersheet",
	"type"					: "marker",
	"src"					: "library/marker.png",
	"width"					: 128,
	"height"				: 32,
	"framewidth"			: 32,
	"frameheight"			: 32,
	"framedelay"			: 1,
	"framesperdirection"	: 3,
	"deathframe"			: 0,
	"deathframecount"		: 0,
	"attackframe"			: 0,
	"attackframecount"		: 0,
	"painframe"				: 0,
	"painframecount"		: 0
}
];